### ISSUE TITLE
Housekeeping Druid log files

### ISSUE THREAD

**Issue by soumyajose0784** [apache/druid#10127]
Is there a preferred approach in housekeeping Druid service log files in a production implementation.

Over the period of time, the logs become too large in size causing space issues in server. Simply deleting the logfiles does not seem to resolve the problem, as the process ids of delete command is still running in background

**Comment by FrankChen021** [comment]
Yes after a long time running, the size of log files could be a problem. There're two ways to clean the logs

1. use `logrotate` to rotate the log file and then create a `crontab` task to delete old enough log files

2. config log4j2 to output log to files so that log files can be deleted based on your configurations. 
to do that, if nodes are started by `broker.sh` or `historical.sh` etc, modify the `node.sh` script shell to redirect stdout of java to /dev/null, and then change log appender of `log4j2` from console to `RollingFileAppender`

In my opinion, druid should use `RollingFileAppender` in its default configuration.

**Comment by giom-l** [comment]
Here is a detailed solution that I implemented in our production Druid (0.15.1) and logs never have been an issue at all. Always rotated properly 
https://webcache.googleusercontent.com/search?q=cache:rIfskAblx68J:https://support.imply.io/hc/en-us/articles/360006216874-How-to-config

**Comment by FrankChen021** [comment]
@giom-l you have done what the PR above intends to do. Thanks for your sharing.
