### ISSUE TITLE
Upgrade AWS SDK

### ISSUE THREAD

**Issue by mitchlloyd** [apache/druid#10375]
### Description

Druid currently uses the 1.11.199 version of the AWS SDK and I need a feature available in a later version of the SDK.

I need the feature in the AWS SDK that allows applications to use [the AWS_STS_REGIONAL_ENDPOINTS environment variable to configure regional STS endpoint usage](https://docs.aws.amazon.com/credref/latest/refdocs/setting-global-sts_regional_endpoints.html). I'm deploying Druid in an environment where I cannot use global STS endpoints because using regional endpoints is a [documented best practice from AWS](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html). This environment variable configuration feature is [available in version 1.11.658 and later](https://github.com/aws/aws-sdk-java/issues/2362#issuecomment-647835178).

### Motivation

I would like to move off of my Druid fork and back onto an official Druid version some day. Upgrading the AWS SDK in Druid brings me one step closer to that goal.

### Solutions

I'm currently running a fork of Druid based on 0.17.1 that uses version 1.11.854 of the AWS SDK. I use Kinesis supervisors, S3 for long-term segment data, and a custom CloudWatch event emitter that all appear to be working.

Would the maintainers be open to a PR that updates the AWS SDK to 1.11.854?

I also opened [a PR to add STS endpoint configuration](https://github.com/apache/druid/pull/10218) before I knew about this environment variable option. That PR adds new configuration which puts more burden on Druid users to find and configure settings for STS in ingest specs. Upgrading the AWS SDK avoids adding new ingest spec configuration options.

**Comment by suneet-s** [comment]
I'm +1 on upgrading the AWS SDK 🎉 We have a bunch of integration tests for Kinesis and S3, so we could run through the entire test suite to see if there are any issues. 

Have you thought about what the test plan should look like for this upgrade?

**Comment by jihoonson** [comment]
The last update on the AWS version was done in https://github.com/apache/druid/pull/5382. It would be fine to upgrade to any version as long as everything works fine :slightly_smiling_face:. The pain point was testing Hadoop indexing since you need to test against different versions of Hadoop. I'm open to dropping support for old versions of Hadoop like 2.7 if they conflict to the new AWS version.

**Comment by suneet-s** [comment]
@mitchlloyd These tests don't run by default on every PR because we need to provide credentials to the cloud provider. There are some instructions written up here on how to run these tests with your credentials - hope this helps. I think I've run them once for Kinesis a few months ago

https://github.com/apache/druid/blob/master/integration-tests/README.md#running-a-test-that-uses-cloud

**Comment by jihoonson** [comment]
@mitchlloyd unfortunately, we don't have such automated tests. However, we do have some integration test for Hadoop indexing. You can run the same tests with varying Hadoop versions. The easiest way I can come up with is preparing docker images of different Hadoop versions and run the same tests with them. You can find how to run Hadoop integration tests in the document @suneet-s linked.
