### ISSUE TITLE
Why druid expects data files to be available on all data servers

### ISSUE THREAD

**Issue by averma111** [apache/druid#10442]
Druid 0.18.1.

Hi Team,

I have a general question. I have cluster setup with 1 master 2 data and 1 query node. I wanted to know why I need place a csv files on both data nodes to be read by Druid for data ingestion?

1.Does Druid reads the data from both files?
2.Does only 1 data nodes reads data from file?

Thanks,
Ashish

**Comment by FrankChen021** [comment]
I don't think the files should be placed on a query or a historical node. But both middle manager and coordinator/overlord node are needed. 

Because there's a sampling processing when create a task from the web console, and sampling is executed on coordinator/overlord node. Once the ingestion task is submitted, it will be scheduled on any middle manager nodes which means we have to place the files on all middle manager nodes.

**Comment by averma111** [comment]
@FrankChen021 --- but in the cluster mode we have datanode having both (historical as well as middlemanger) running , thats the reason I wrote data node.
Also tell me if I have 2 middle managers which one will be used(decided by zookeeper as LB)?


Thanks,
Ashish

**Comment by FrankChen021** [comment]
There're some strategies used by overlord nodes to select a worker to execute a task, see **[Worker Select Strategy](https://druid.apache.org/docs/latest/configuration/index.html#overlord-dynamic-configuration)**  here. The default strategy is `Equal Distribution` which means tasks are load balanced among middle managers.

**Comment by averma111** [comment]
@FrankChen021  Thank you for the prompt response , I got what I wanted to know
