### ISSUE TITLE
Druid doesn't mark segments as "unused" when converting from a higher segment granularity to a lower segment granularity.

### ISSUE THREAD

**Issue by damnMeddlingKid** [apache/druid#10553]
### Affected Version

tested on Druid v0.19

### Description

According to the [documentation](https://druid.apache.org/docs/latest/tutorials/tutorial-compaction.html#compact-the-data-with-new-segment-granularity) using a compaction task to change the segment granularity of data will mark the old segments as unused.

 While testing this out I've noticed that segments don't get marked as unused when converting a higher segment granularity (Month) to a lower segment granularity (Day).

Steps to reproduce:

1) create a datasource with some data at a monthly granularity
2) run a compaction task like 

```
{
	"type": "compact",
	"dataSource": "your_datasource",
	"interval": "2020-10-01T00:00:00.000Z/P1M",
	"segmentGranularity": "DAY"
}
```

3) query the metadata store using 

```
select start, used, datasource from druid_segments where datasource='your_datasource';
```

expected: segments that start on the month are marked as used=false
actual: all segments have used=true

**Comment by maytasm** [comment]
This can be a result of the new DAY segments not fully covering the Month.
For example if you have MONTH segment with 2020-10-01 to 2020-11-01 and you don't have data on every day in the month (for example, the only data rows you have are on 2020-10-08 to 2020-10-09), then Druid would only create new DAY segments for day with data (in the above example, you would only get one new segment 2020-10-08 to 2020-10-09). 
Since Druid do not see DAY segments for every day of the month, Druid cannot mark unused the old MONTH segment.
