### ISSUE TITLE
Dimension VS Metric, Sketches and Rollups

### ISSUE THREAD

**Issue by amirvaza** [apache/druid#10586]
Following this video from FJ at 39:20:
https://youtu.be/vbH8E0nH2Nw?t=2360

FJ mentions that in this example they ingested `UserId` both as a Dimension and as a Metric(Sketched).

As I understand it, in any case, after rollup of course, the sketch column will store only one value, the same value as in the UserId **dimension**.
My question is, whats the point of doing so? 
Why not just using the `UserId` dimension and create the sketch during query time?

Thanks.

**Comment by vogievetsky** [comment]
Your understanding is correct! if `UserId` is a dimensions then a sketch(UserId) would always represent just one UserId. It is maybe not the best example.

There is still a reason you might want to do it - for performance!
In short `APPOX_COUNT_DISTINCT(userId_sketch)` would computer faster than `APPOX_COUNT_DISTINCT(userId)` as the userId_sketch is already semi-digested even if it is just for that one user_id. Since Druid users love performance more than they love their mother it is not uncommon to see this pattern.
