### ISSUE TITLE
Vectorizing extraction dimension specs

### ISSUE THREAD

**Issue by a2l007** [apache/druid#10594]
The vectorization query engine in Druid presently doesn’t support vectorization of extraction dimension specs.
I’m in the process of coming up with a design proposal for adding this support. Reviewing the `VectorGroupByEngineIterator` flow, it looks like there isn’t a direct way to support this because after the vectorized aggregation within a cursor, the dimensions are lazily resolved for each result row based on the dimension ID. 
For vectorizing the dimension resolution, `DimensionDictionarySelector` implementations would start handling a vector of dimension keys which can be further used by the extraction functions to perform the resolution.
The new lookup definition would be something like:

`Memory lookup(Memory keySpace, int keySize, int keyOffset, int startRow, int endRow)`

The resolved dimension values returned by the lookup method would have to be held in a writable memory space similar to the existing [keyspace](https://github.com/apache/druid/blob/master/processing/src/main/java/org/apache/druid/query/groupby/epinephelinae/vector/VectorGroupByEngine.java#L232).  Unlike the [grouping key size](https://github.com/apache/druid/blob/master/processing/src/main/java/org/apache/druid/query/groupby/epinephelinae/vector/GroupByVectorColumnSelector.java#L36) for keys in the keyspace, the size of the resolved dimension values may vary and so each size would also have to be held in the dimension valueSpace along with the resolved dimension values.

Finally, while writing into the result row, the iterator used within the query engine ( for example: [VectorGroupByEngineIterator](https://github.com/apache/druid/blob/master/processing/src/main/java/org/apache/druid/query/groupby/epinephelinae/vector/VectorGroupByEngine.java#L442)) can read the dimension value from the dimension valueSpace with the appropriate offset instead of doing a [DictionarySelector.lookupName](https://github.com/apache/druid/blob/master/processing/src/main/java/org/apache/druid/segment/column/StringDictionaryEncodedColumn.java#L368). 

@gianm , @clintropolis : It would be really helpful to get your thoughts on this approach. The concern I have here is regarding holding the dimension valueSpace in memory as this can eat into the off heap memory usage significantly depending upon the number of query dimensions and its cardinality.

**Comment by clintropolis** [comment]
Moderately related, I have been working on a 'dictionary building' vector grouping strategy for string columns from my work related to vectorizing expressions, which I think is solving more or less the same problem (since string expressions also cannot use the dictionaryId as the grouping key). I think that might also be able to solve the lookup problem, though I haven't really thought about it very much yet in the context of lookups.

I've been busy with some other stuff so haven't touched the code in over a month, but I think I should have a chance to wrap it up maybe next week, assuming testing goes as I hope. In the meantime, I'll try to think a bit more about lookups and if my work would truly be applicable here.

**Comment by a2l007** [comment]
@clintropolis Sounds interesting. In the current state of the PR, does the dictionary building strategy apply for vectorizing string columns in general or is it supported only for string expressions? In addition to lookups, It would be interesting to see how we can leverage the grouping strategy to support other extraction function types as well.
