### ISSUE TITLE
double quoting string values in SQL WHERE clause gives "org.apache.calcite.runtime.CalciteContextException"

### ISSUE THREAD

**Issue by erickj** [apache/druid#10619]
Please provide a detailed title:

double quoting string values in SQL WHERE clauses result in a exception:

"org.apache.calcite.tools.ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 1, column 49 to line 1, column 53:"

single quoting the value yields the expected result. example below

### Affected Version

0.20.0 running in a standalone single-server

### Description

Very strange issue here. I have a table (schema below) with a varchar 'ticker' column. When I run a query I must use single-quote characters around values for ticker. If I use double quotes I get the following error.

Output copied from dsql:
```
dsql> SELECT count(*) FROM "stocks-5k" WHERE ticker = "AHH";
org.apache.calcite.tools.ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 1, column 49 to line 1, column 53: Column 'AHH' not found in any table
dsql> SELECT count(*) FROM "stocks-5k" WHERE ticker = 'AHH';
┌────────┐
│ EXPR$0 │
├────────┤
│    692 │
└────────┘
```

table schema:
```
__time TIMESTAMP
count BIGINT
sum_adj_close DOUBLE
sum_close DOUBLE
sum_high DOUBLE
sum_low DOUBLE
sum_open DOUBLE
sum_volume BIGINT
ticker VARCHAR
```

**Comment by FrankChen021** [comment]
This issue is more relevant to SQL standard.

According to SQL standard, double quoted strings refer to object names, which are usually name of tables or columns while single quoted strings refer to string value which are usually used in an expression or as an input argument of a function.

In your first SQL, "AHH" is double quoted, Calcite(the SQL parser) treats it as a column name which obviously does not exist in table `stocks-5k` and throws the exception that you see.

Table names or column names are not necessarily double quoted if they only contains letters and underscores.

```
SELECT count(*) FROM "stocks" WHERE ticker = 'AHH' 
```

is equivalent to 

```
SELECT count(*) FROM stocks WHERE ticker = 'AHH' 
```

But if there're spaces or other special characters like hyphen('-') in the names(`stocks-5k` in your example), the name must be double quoted or the SQL can't be parsed correctly.

**Comment by vogievetsky** [comment]
There is a feature in the next release of the web console made especially for you!

![image](https://user-images.githubusercontent.com/177816/101268176-191b6a00-3715-11eb-8761-0f4feadb48e6.png)

Notice:

![image](https://user-images.githubusercontent.com/177816/101268185-25072c00-3715-11eb-963a-9ea06402441e.png)

If you click it it will do it!
