### ISSUE TITLE
Druid DR Plan

### ISSUE THREAD

**Issue by soumyajose0784** [apache/druid#10621]
Is there any documentation on the Disaster Recovery Plan for Druid? 

We have multi-cluster Druid implementation with 2 datanodes, 1 master and 1 query node, with mysql as metadata storage.

**Comment by himanshug** [comment]
DR plan is to basically ensure that Druid cluster nodes are stateless.

Just make sure you have DR plans for metadata store and deep storage ... as long as they are available you should be able to bring up a brand new Druid cluster pointing to those to get everything back.

make sure to set `druid.indexer.storage.type=metadata` at overlord so that it stores task state in metadata store and also
if you want to retain completed task logs after DR then push them outside of Druid nodes by setting `druid.indexer.logs.type` probably to same deep storage. (Ref https://druid.apache.org/docs/latest/configuration/index.html for more information on those configuration)

**Comment by soumyajose0784** [comment]
@himanshug  , thank you for your inputs.

**Comment by soumyajose0784** [comment]
DR plan is made with Relevant DR on metadata db and deep storage
