### ISSUE TITLE
TieredBrokerHostSelector - No brokerServiceName found for datasource

### ISSUE THREAD

**Issue by linehrr** [apache/druid#10773]
### Affected Version

0.18.1

### Description

router logs have error like this:

`2021-01-18T02:00:54,040 ERROR [qtp1532989443-88] org.apache.druid.server.router.TieredBrokerHostSelector - No brokerServiceName found for datasource[Report], intervals[[2021-01-14T09:00:00.000Z/2021-01-14T10:00:00.000Z]]. Using default[druid/broker].`

no idea about how this happened. and there are no other logs that's useful. 
queries most of the time succeeded. because looks like `using default[druid/broker]` works. however some queries sporadically fails, return code is HTTP 503. 
other than this we don't see other error logs, so we thought this could be related.

**Comment by machine424** [comment]
I think you need to set `druid.router.tierToBrokerMap`, see [here](https://druid.apache.org/docs/latest/configuration/index.html#runtime-configuration) otherwise the router will "not find" the corresponding broker to take care of your query in the map, log an error and fallback to `druid.router.defaultBrokerServiceName`

relevant code: https://github.com/apache/druid/blob/druid-0.20.2/server/src/main/java/org/apache/druid/server/router/TieredBrokerHostSelector.java#L192-L244 (druid 0.20.2)

**Comment by kfaraz** [comment]
The level of this log has been reduced in PR https://github.com/apache/druid/pull/14368 as it was not really an error in the first place. It will be included in the upcoming release of Apache Druid 27.

Configuring `druid.router.tierToBrokerMap` is not mandatory and can silently default to `druid/broker` on its own.

Closing this issue.
