### ISSUE TITLE
Does druid.io sql query support group_concat?

### ISSUE THREAD

**Issue by dbsd11** [apache/druid#10800]
Try to build single result of group by result on string column, but it doesn't works and reports error: No match found for function signature group_count(< CHARACTER >)

Query sql example is below:
select group_concat(b) from (select 'aa' as a, 'bb' as b UNION ALL (select 'aa' as a, 'bbb' as b)) group by a;

Error: Unknown exception

org.apache.calcite.runtime.CalciteContextException: From line 5, column 8 to line 5, column 22: No match found for function signature group_concat(<CHARACTER>)

org.apache.calcite.tools.ValidationException

**Comment by abhishekagarwal87** [comment]
There is no support from the `group_concat` function as of today. One challenge with implementing such a function is that size of the aggregated value is not constant across rows. Users can pass a maximum size as input but that can lead to inefficient usage of memory since druid also doesn't support growable buffers as of yet.

**Comment by jihoonson** [comment]
Hi @dbsd11, `group_concat` is not supported yet as @abhishekagarwal87 mentioned. You can see what functions are supported in https://druid.apache.org/docs/latest/querying/sql.html.

**Comment by dbsd11** [comment]
I see. Thank you for your answer. Can I implement this through custom aggregation plugin?

**Comment by dbsd11** [comment]
I implement druid.io group_concat by custom avatia client. Firstly, execute sql without group_concat. Then, group_concat results at client. Can druid.io avatica server implement this function, rather than by user client?
