### ISSUE TITLE
Handling unparsed records in kafka ingestion

### ISSUE THREAD

**Issue by soumyajose0784** [apache/druid#10970]
Is there a suggested approach to handle record rejections in kafka ingestion.  Whats the best approach to reprocess the unparsed records in streaming job.  Is there a way to log the rejected data for reference and later reprocessing without enabling verbose settings.

**Comment by FrankChen021** [comment]
What's the format of records in Kafka, JSON ? If it's JSON, I think there won't be such exceptions because producers always use some JSON library to produce well-formatted messages.

So in our systems, we don't care such exceptions and have no advice for you how to handle these exceptions. 

But I know there's a parameter [logParseException](https://druid.apache.org/docs/latest/development/extensions-core/kafka-ingestion.html#kafkasupervisortuningconfig), which I have never used before, provided in supervisor to log unparsed records.

**Comment by sub007** [comment]
> Is there a way to log the rejected data for reference
Yes, `logParseException : true` can help you. It logs messages such the one below along with the input data.
Eg.,
_2021-03-15T10:13:57,575 ERROR [task-runner-0-priority-0] org.apache.druid.segment.incremental.ParseExceptionHandler - Encountered parse exception
org.apache.druid.java.util.common.parsers.ParseException: Found unparseable columns in row: ..._

**Comment by nikunjratanpara** [comment]
I have logParseException : true and We know why it is unparsed but ingestion get halted with Tasks failing , It is not skipping that event from kafka. 
Is there a way I can skip that record and ingest others?

Below is my ingestion spec.
{
  "type": "kafka",
  "dataSchema": {
    "dataSource": "data-source",
    "parser": {
      "type": "string",
      "parseSpec": {
        "format": "json",
        "timestampSpec": {
          "column": "timestamp",
          "format": "auto"
        },
        "dimensionsSpec": {
          "dimensions": [
            "dimention1",
			"dimention2",
          ]
        }
      }
    },
    "metricsSpec": [],
    "granularitySpec": {
      "type": "uniform",
      "segmentGranularity": "DAY",
      "queryGranularity": {
        "type": "none"
      },
      "rollup": false
    }
  },
  "tuningConfig": {
    "type": "kafka",
    "logParseExceptions": true,
    "maxSavedParseExceptions": 1
  },
  "ioConfig": {
    "topic": "kafka-topic",
    "consumerProperties": {
      "bootstrap.servers": "kafka:9093",
    }
  }
}
