### ISSUE TITLE
Druid Tasks UI breaks when there are so many tasks records

### ISSUE THREAD

**Issue by didip** [apache/druid#11042]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

0.20.1

### Description

When Druid has too many tasks (failed/successful), the Tasks UI would often failed to load.

My work around is to lower druid.indexer.storage.recentlyFinishedThreshold to PT30M.

**Comment by FrankChen021** [comment]
I didn't know what exact error you encountered. Did it take too long for the servers to return the tasks to the UI ? or Did it take too long for the web-console to render UI while the servers response in very short time? And how many tasks are there ?

And if it's the former one, maybe there's a way to improve it. Current task UI loads all tasks from router and does paging at client side. An optimization could be applied here, that is loading the tasks from server one page by one page by adding LIMIT/OFFSET clause to the sql. Since the default page size is 20, I think this would greatly reduce the data returned by servers and also reduce the time that the servers handle the query. 

If this is the problem you met, you could do a test by adding LIMIT/OFFSET to the sql and post the query to the router to see if it saves time

**Comment by vogievetsky** [comment]
I believe https://github.com/apache/druid/pull/12404 greatly improved the situation here. Please re-open if you see this post 24.0
