### ISSUE TITLE
How to improving ingestion performance

### ISSUE THREAD

**Issue by zhangyouxun** [apache/druid#11061]
peon config :
-Xms10g -Xmx10g -XX:+UseG1GC -XX:MaxDirectMemorySize=10g -Duser.timezone=UTC -Dfile.encoding=UTF-8 -XX:+ExitOnOutOfMemoryError -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
druid.peon.defaultSegmentWriteOutMediumFactory.type=offHeapMemory
druid.indexer.fork.property.druid.processing.numThreads=2
spec:
    "tuningConfig": {
      "maxRowsInMemory": 1000000,
      "maxBytesInMemory": 0,
      "maxRowsPerSegment": 5000000
    }
row size:  300bytes
peon ingest speed： 5k/s
taskCount：30

is there any wrong param leading low ingestion？
How to improve the speed of ingestion？

**Comment by FrankChen021** [comment]
Your task count is 30, does that mean there're 30 partitions of your topic ? And is the ingestion speed 5K/s of per peon ? Even it's 5K/s per peon, it's not a very high speed that it needs 10G heap size for each peon. 4G is enough in our clusters to handle messages at much higher speed.

Since streaming ingestion speed is more relevant to streaming middleware, tuning producer and consumer may help. Are you using Kafka ? And what parameters you have adopted to configure Kafka producers and consumers ?

**Comment by zhangyouxun** [comment]
> Your task count is 30, does that mean there're 30 partitions of your topic ? And is the ingestion speed 5K/s of per peon ? Even it's 5K/s per peon, it's not a very high speed that it needs 10G heap size for each peon. 4G is enough in our clusters to handle messages at much higher speed.
> 
> Since streaming ingestion speed is more relevant to streaming middleware, tuning producer and consumer may help. Are you using Kafka ? And what parameters you have adopted to configure Kafka producers and consumers ?

the num of partitions is 270.
The maxBytesInMemory is about 300Mb, is it not make full use of heap?

we use Kafka
max.poll.records = 500
max.partition.fetch.bytes = 1048576
fetch.max.bytes = 52428800
fetch.max.wait.ms = 500
fetch.min.bytes = 1
metadata.max.age.ms = 10000
which parameter needs to be adjusted？

**Comment by FrankChen021** [comment]
> the num of partitions is 270.

It's better to check whether your messages are evenly distributed among these partitions. If not, some peons will process more messages than others, there might be some lags for these peons.

> The maxBytesInMemory is about 300Mb, is it not make full use of heap?

In your spec, this parameter is 0, which will be default to 1/6 of JVM max heap size during running. Persistence happens when either `maxRowsInMemory` or `maxBytesInMemory` is reached.  But persistence is running in a separated thread, I don't think these two affect the ingestion speed.

For Kafka, generally speaking, there're 2 parameters which I usually highly recommend to use to improve throughput 
1. set `compression.type` to lz4 at producer side. This would greatly reduce network traffic without introducing extra CPU usage at producer and consumer side.
2. set `fetch.min.bytes` to a large number(such as 4096) to tell brokers return more messages in a single fetch response to a consumer . This would greatly reduce network requests/responses between consumers and brokers.

**Comment by zhangyouxun** [comment]
> set compression.type
After verification, modify this parameter to increase the consumption speed to 7.5k/s.

Use 10G heap, how to make full use of memory to increase speed?

**Comment by zhangyouxun** [comment]
> > the num of partitions is 270.
> 
> It's better to check whether your messages are evenly distributed among these partitions. If not, some peons will process more messages than others, there might be some lags for these peons.
> 
> > The maxBytesInMemory is about 300Mb, is it not make full use of heap?
> 
> In your spec, this parameter is 0, which will be default to 1/6 of JVM max heap size during running. Persistence happens when either `maxRowsInMemory` or `maxBytesInMemory` is reached. But persistence is running in a separated thread, I don't think these two affect the ingestion speed.
> 
> For Kafka, generally speaking, there're 2 parameters which I usually highly recommend to use to improve throughput
> 
> 1. set `compression.type` to lz4 at producer side. This would greatly reduce network traffic without introducing extra CPU usage at producer and consumer side.
> 2. set `fetch.min.bytes` to a large number(such as 4096) to tell brokers return more messages in a single fetch response to a consumer . This would greatly reduce network requests/responses between consumers and brokers.

![image](https://user-images.githubusercontent.com/37095921/113384645-1544df00-93b9-11eb-882b-eb6e8e353c80.png)
 还有其他参数可以优化吗？
is there any parameter needed adjust?

**Comment by FrankChen021** [comment]
> After verification, modify this parameter to increase the consumption speed to 7.5k/s.

Glad to see that it helps.

> Use 10G heap, how to make full use of memory to increase speed?

You could try to increase `maxRowsInMemory`, `maxBytesInMemory` `maxRowsPerSegment`.

**Comment by FrankChen021** [comment]
> is there any parameter needed adjust?

I have no other advices for you on other parameters since most of them are not relevant to throughput. 

Because there're 270 partitions of your topic, have you checked that network bandwidth among producers/kafka brokers/consumers is enough ? And if it's enough, I think you could increase task count to improve parallelism. But considering your heap size configuration, it's better to lower down it before you increase the task count.
