### ISSUE TITLE
How to load extension only to the broker

### ISSUE THREAD

**Issue by rec7y33** [apache/druid#11086]
Hi everyone, how do I load extension only to the broker? as stated here: https://druid.apache.org/docs/latest/development/extensions-contrib/moving-average-query.html#operations

`To use this extension, make sure to load druid-moving-average-query only to the Broker.`

Thanks

**Comment by JulianJaffePinterest** [comment]
Assuming you have your configuration files laid out in the [recommend manner](http://druid.apache.org/docs/latest/configuration/index.html), just add the moving average extension to the `druid.extensions.loadList` in `conf/druid/broker/runtime.properties` as opposed to `conf/druid/_common/common.runtime.properties`.

**Comment by Kinigopoulos** [comment]
Hello,
I try to load the extension to the broker but when I start druid, it seems that it isn't loading because the queryType doesn't exist.
I am using version 0.21.0 but I have used previous ones as well. The result is unfortunately the same.

In the `conf/druid/broker/runtime.properties` file, I added `druid.extensions.loadList=["moving-average-query"]` at the top.
I am using the micro-quickstart configuration and I haven't changed anything else from there.

Java version (if for some reason that's what causes it): openjdk 1.8.0_292

I would be glad if someone could help.
Thanks in advance!

**Comment by FrankChen021** [comment]
@Kinigopoulos there're something you could check.

**Comment by Kinigopoulos** [comment]
@FrankChen021 thanks for the reply.
It seems that, indeed, the broker loads the extension.
However, how do I send queries to the broker? Is there a way from the web-based UI?

**Comment by FrankChen021** [comment]
> @FrankChen021 thanks for the reply.
> 
> It seems that, indeed, the broker loads the extension.
> 
> However, how do I send queries to the broker? Is there a way from the web-based UI?

queries can't be sent to broker from the web console. You could find the broker IP address on the Services Tab on web console,and send queries to that address.

**Comment by Kinigopoulos** [comment]
Ok, so I send to `localhost:8082/druid/v2` a request from the examples of the extension's website page to test if it's working and I am getting back:
```
{
  "error": "Unknown exception",
  "errorMessage": "org.apache.druid.java.util.common.NonnullPair cannot be cast to java.util.concurrent.ConcurrentHashMap",
  "errorClass": "java.lang.ClassCastException",
  "host": null
}
```

**Comment by FrankChen021** [comment]
Looks like there's a bug. I will investigate it later.

**Comment by FrankChen021** [comment]
@Kinigopoulos There is an issue(#10799) reporting this problem. Any messages about this problem will be updated there. Thanks.
