### ISSUE TITLE
Opentracing / Opentelemetry Support

### ISSUE THREAD

**Issue by midnightconman** [apache/druid#11246]
### Description

How does the apache druid project feel about tracing support in Druid? As tracing gains more traction in the industry, more and more applications are relying on it to provide insight into the timings of the various functions and how long various activities take.  

Opentelemetry is a pretty popular tracing library (with java) support these days : https://github.com/open-telemetry/opentelemetry-java

### Motivation

The ability to send tracing data from druid components to a tracing provider / backend. This would help in tracking and improving function timing for druid.

**Comment by FrankChen021** [comment]
This is an interesting topic. I'm going to do this in my Druid cluster to improve observability.

In contrast to provide such ability by Druid itself, it's highly recommended to use some non-intrusive(auto instrumentation) solutions such as [PinPoint](https://github.com/pinpoint-apm/pinpoin) to achieve this goal.  As I know, pinpoint works very well with Jetty used by Druid. If I understand correctly, open telemetry also provides auto instrumentation.

So the only thing we have to do is putting java agent of those tools mentioned above to the java command line of Druid services. But one thing that I think we need to make little change is at the peon command line. It's better to set different application name, which will be reflected at the observability platform,  for each task based on their datasource so that it's more clear that a query goes into which task.

**Comment by manigarg31** [comment]
Any update on this feature?
