### ISSUE TITLE
Druid 0.20.2 failing jobs due to parsing exception

### ISSUE THREAD

**Issue by Murthy7587** [apache/druid#11295]
We have recently upgraded from druid version 0.19 to 0.20.2 after which we are seeing issues while ingestion of data through kafka. 

If any of the event has issue with parsing, entire job is been failed by the system.
We have kept "reportParseExceptions" as false, but still we are seeing ingestion getting failed if any incoming record is having parsing issues.

This was working fine in version 0.19 incubation.

**Comment by asdf2014** [comment]
Hi, @Murthy7587. Thank you for reporting this issue. Could you please provide the content of the task and the error log for analyzing?

**Comment by Murthy7587** [comment]
Hi,

Please find attached the indexing-task logs. Hope this suffices.
[index_kafka_EPC_Raw_9c0301ab8d8ffbe_gdnfkbfa.log](https://github.com/apache/druid/files/6537890/index_kafka_EPC_Raw_9c0301ab8d8ffbe_gdnfkbfa.log)

**Comment by FrankChen021** [comment]
@Murthy7587 From the log, I notice that the old parser spec is used. 

```
    "parser" : {
      "type" : "string",
      "parseSpec" : {
        "format" : "json",
        "timestampSpec" : {
          "column" : "CreationTime",
          "format" : "ddMMyyyyHHmmss"
        },
        "dimensionsSpec" : {
          "dimensions" : [ "COUNTER_GROUP_ID", "EPC_P_1", "EPC_P_2", "EPC_P_3", "EPC_P_4", "EPC_P_5", "EPC_P_6", "EPC_P_7" ],
          "dimensionExclusions" : [ "CreationTime" ]
        }
      }
    }
```

The exception handling for this old parser spec may not be handled well, and since this kind of parser has been deprecated since 0.17.0 ,  I'm suggesting you that you make some change to your supervisor spec to utilize the newer JSON `inputFormat` spec which I think addresses your problem here.

See the [doc](https://druid.apache.org/docs/latest/ingestion/data-formats.html#parser) here.
