### ISSUE TITLE
Cannot ingest Protobuf file on version 0.21.1

### ISSUE THREAD

**Issue by steliosph** [apache/druid#11537]
It appears that ingesting of Protobuf files on the latest version of Druid is broken.

The default ingestion used from the help page will not work either
https://druid.apache.org/docs/latest/development/extensions-core/protobuf.html

On version 0.20.2
![image](https://user-images.githubusercontent.com/3367401/127987219-07df1721-9b31-45c9-a7ac-eb3c31a46934.png)

While on the latest version 0.21.1
![image](https://user-images.githubusercontent.com/3367401/127994362-ebe35e4b-1b37-4b94-916b-38af235f18f8.png)

To reproduce simply copy-paste the  parse in the ingestion spec.

**Comment by bananaaggle** [comment]
I test it and reproduced it with master branch. At first, I think there is some bug in code. Secondly, `parser` will be deprecated, I'll update this document with `inputformat` in week.

**Comment by steliosph** [comment]
Hi @bananaaggle,

Thank you for the time.
Input format documentation states that it does not support all data formats.
https://druid.apache.org/docs/latest/ingestion/data-formats.html#input-format

Has this been altered as well in order to accomodate the protobuf handling and also Hadoop ingestion ?

**Comment by bananaaggle** [comment]
Because of [10647](https://github.com/apache/druid/pull/10647), supervisor properties with `parser` does not work in 'Load data' tab in frontend. There is a frontend verification avoid you submit supervisor properties. In next release, `inputFormat` is adapted to protobuf and I change document in [11545](https://github.com/apache/druid/pull/11545) for it. Now `parser` can be used in 0.21.1 and you can submit your supervisor properties json in 'Ingestion' tab as showed below, where is with no verification.
<img width="857" alt="Screen Shot 2021-08-04 at 4 20 48 PM" src="https://user-images.githubusercontent.com/24642075/128147870-8ff98209-341d-4c42-8ee8-349fe94fcba7.png">
