### ISSUE TITLE
[Draft] 0.22.1 Release Notes

### ISSUE THREAD

**Issue by jihoonson** [apache/druid#12054]
Apache Druid 0.22.1 is a bug fix release that fixes some security issues in the 0.22 release. [See the complete set of changes for additional details](https://github.com/apache/druid/milestone/44?closed=1).

## <a name="22-1-bug-fixes" href="#22-1-bug-fixes">#</a> Bug fixes
https://github.com/apache/druid/pull/12051 Update log4j to 2.15.0 to address [CVE-2021-44228](https://nvd.nist.gov/vuln/detail/CVE-2021-44228)
https://github.com/apache/druid/pull/11787 JsonConfigurator no longer logs sensitive properties
https://github.com/apache/druid/pull/11786 Update axios to 0.21.4 to address [CVE-2021-3749](https://nvd.nist.gov/vuln/detail/CVE-2021-3749)
https://github.com/apache/druid/pull/11844 Update netty4 to 4.1.68 to address [CVE-2021-37136](https://nvd.nist.gov/vuln/detail/CVE-2021-37136) and [CVE-2021-37137](https://nvd.nist.gov/vuln/detail/CVE-2021-37137)

## <a name="22-1-credits" href="#22-1-credits">#</a> Credits
Thanks to everyone who contributed to this release!

@abhishekagarwal87
@andreacyc
@clintropolis
@gianm
@jihoonson
@kfaraz
@xvrl

**Comment by krishnat2** [comment]
Thanks for the quick fix. Do you guys think, we can also have a 0.21.1 Hotfix ?

**Comment by jihoonson** [comment]
Hi @krishnat2, at least as of now, we are not planning hotfix releases for older versions than 0.22.0. You may want to use the options suggested by the log4j community (https://lists.apache.org/thread/bfnl1stql187jytr0t5k0hv0go6b76g4) if you cannot upgrade immediately. Especially the second option that uses %m{nolookups} in the PatternLayout configuration looks promising.

**Comment by gianm** [comment]
The branch also has #11844 (netty update due to CVE).

thanks @jihoonson!

**Comment by glasser** [comment]
To be clear, I think @jihoonson is recommending the second option because the first (much easier to use) option won't work on the older version of log4j2 from before #12051.

We would appreciate the 0.21 backport as well (although we of course do want to get to 0.22 too).

**Comment by glasser** [comment]
One thing that's challenging about the PatternLayout recommendation (especially as a non-log4j2-expert) is understanding if paths that don't use PatternLayout at all are safe or not.  For example, our log4j2.xml looks in part like:

```
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <JsonLayout
        complete="false"
        compact="true"
        eventEol="true"
        properties="true"
      />
    </Console>
    <RollingRandomAccessFile name="Server"
                 fileName="/tmp/server.${sys:druid.plaintextPort:-0}.log"
                 filePattern="/tmp/server.${sys:druid.plaintextPort:-0}.%i.log.gz">
      <PatternLayout pattern="%d{ISO8601} %p [%t] %c - %m%n"/>
      <Policies>
        <SizeBasedTriggeringPolicy size="100 MB"/>
      </Policies>
      <DefaultRolloverStrategy max="10"/>
    </RollingRandomAccessFile>
  </Appenders>
```

I can see that we can add the `%m` thing to the PatternLayout inside RollingRandomAccessFile.  We don't use PatternLayout inside Console, though — we use JsonLayout. Does that mean that the Console part of our configuration is safe because the *problem* is PatternLayout-specific, or that this part of our configuration is broken and there's no way to fix it?

(This level of complexity is why we would appreciate a backport if feasible, though we can probably also just do our own build of "0.21.1 + #12051" for now.)

**Comment by gianm** [comment]
Yes, the second option is recommended because prior to 0.22.1, Druid used log4j 2.8.2, which doesn't accept the `-Dlog4j.formatMsgNoLookups=true` mitigation. But according to the log4j maintainers, it does accept the `%m{nolookups}` mitigation.

@glasser typically for security issues we patch the latest version, and for earlier versions we're more likely to recommend deploying mitigations. Even if that does change we are definitely going to be prioritizing getting out the 0.22.1 release.

In your specific case, a couple of thoughts:

1. The issue https://issues.apache.org/jira/browse/LOG4J2-3198, and the attached PR, makes it appear to me that the problem is PatternLayout-specific.
2. However, I wouldn't trust my own rookie analysis here! So in your position, if I wasn't comfortable upgrading to 0.22.1 today, instead I'd manually replace the 2.8.2 jars in my local install with the 2.15.0 jars. It should work OK, since when we updated master to 2.15.0, we didn't need to change any source code. It suggests the 2.15.0 jars should work as a drop in replacement. Or, if you can build your own tarball, I'd do one of 0.21.1 with the log4j version updated.

**Comment by glasser** [comment]
Yeah, we are probably going to do something like the latter, but I suspect there are folks whose Druid deploy/build system is less flexible than ours who also haven't upgraded to the release from less than 2 months ago who might find this challenging. (But also I probably don't need to be trying to make this point both here and on the dev list.)

**Comment by glasser** [comment]
(But you're right that https://github.com/apache/logging-log4j2/pull/607#issuecomment-981973603 strongly suggests that our JsonLayout use case is OK.)

**Comment by yurmix** [comment]
Is any of the other prs in this release related to #12051 ? (In case one wishes to attempt backporting by building from source).

**Comment by gianm** [comment]
#12051 fixes the vulnerability by upgrading log4j, but introduces a new problem with logger shutdown that we are intending to address with #12056. But I think you could live without that second fix. I don't think it's likely to cause production issues beyond strange-looking logs at shutdown.

**Comment by krishnat2** [comment]
Given the new Vulnerability (https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45046), are we planning on releasing a patch with Log4J 2.16. Please advice.

**Comment by gianm** [comment]
Hi @krishnat2, this is being discussed on the mailing list at: https://lists.apache.org/thread/06np4mml2gvyrdqkfqdjzs2dlp20n7hj

We will be doing a new release with log4j 2.17, the only question is timing. We aren't doing it on the same emergency basis as the 0.22.1 release. The newly disclosed vulnerabilities are less serious, do not affect Druid in its default configuration, & have straightforward mitigations available: restore the pattern to its original state that does not reference context variables. But we will definitely do the update in our next regular release (0.23.0), and possibly sooner (0.22.2). If you are interested, keep an eye on that mailing list thread.
