### ISSUE TITLE
Auto Compaction Tasks Unexpectedly Running in Parallel  (maxNumConcurrentSubTasks=1)

### ISSUE THREAD

**Issue by pchang388** [apache/druid#12055]
### Affected Version
0.22.0

### Description
We have a working Druid cluster running the 0.22.0 version, 
- 5 Middle Managers with 10 peons each (50 total workers)
- According to the formula, we have 5 slots for auto compaction to take place
  -  min(totalWorkerCapacity * compactionTaskSlotRatio, maxCompactionTaskSlots) - default compactionTaskSlotRatio= 0.1
- We have auto compaction enabled for 4 out of 5 of the datasources (with default settings)
- For the 4 enabled datasources they have the "Max num concurrent sub tasks"/maxNumConcurrentSubTasks set to 1
- When auto compaction runs (every 30 minutes by default), only some datasources are run in the interval because there are 2+ auto compaction tasks being launched per datasource instead of the expected 1 per datasource
- I do not see any related error messages in the overlord logs but can attach any log dumps if needed/helpful
- Attached screenshots of relevant settings/examples

**_Since a single datasource is using 2+ tasks (sometimes all 5) out of the available 5 for auto compaction, some of the other datasources are never/rarely being compacted since all the task slots are full_**. 

From what I understood of the documentation, the "Max num concurrent sub tasks"/maxNumConcurrentSubTasks property should be restricting each datasource to 1 task for auto compaction but this does not seem to be the case. 

Any help on understanding/resolving this issue would be appreciated!
![CompactSettings](https://user-images.githubusercontent.com/51681873/145635917-fa10256a-1638-49b0-b3ca-491f4ae99bef.png)
![compactTasks](https://user-images.githubusercontent.com/51681873/145635918-b3bf5fae-83aa-4b95-8de6-c31a037cab47.png)
![DatasourcesOverview](https://user-images.githubusercontent.com/51681873/145635920-02ccc62b-5b98-47b7-b32e-6c7c9fe2cea3.png)

**Comment by maytasm** [comment]
@pchang388 
I suspect that the multiple compaction tasks for the same datasource are running for different intervals. The auto compaction create compaction tasks in order of most recent data regardless of datasource. For example, if you have 5 slots for auto compaction and datasource A with 5 segments of interval 2000-01-01/2000-01-02, 2000-01-02/2000-01-03, 2000-01-03/2000-01-04, 2000-01-04/2000-01-05, 2000-01-05/2000-01-06 and datasource B with 1 segment of interval 1999-01-01/1999-01-02. Auto compaction will create 5 compaction tasks for datasource A, one compaction task for each segment of datasource A. Auto compaction will not create any compaction task for datasource B as all 5 available slots are used for datasource A since all segments of datasource A is more recent than those of the datasource B. 

Do you have segments that needs compaction for datasources that was not run that are more recent than the one being compacted in the tasks?
