### ISSUE TITLE
Improve build performance of modules

### ISSUE THREAD

**Issue by MC-JY** [apache/druid#12485]
Hi, I'm now using **druid**. I found that the build time of the project is not very fast when I used `mvn -T 1C install -DskipTests` command to build the project during Github Actions. So I try to speed up the build performance of the project. The goal here is to clean up dependencies between maven modules in the project in order to improve the build performance.

Thread usage before cleaning up module dependencies was this:
![1](https://user-images.githubusercontent.com/92497220/165312713-2bc45263-e704-4fac-9346-f4fce60dabd7.jpg)

Using `mvn dependency:analyze` command I managed to have an overview of the unused dependencies of every module. I focused only on the dependencies between modules. The following dependencies can be cleaned up:
<pre><code>
org.apache.druid.extensions:druid-basic-security(druid/extensions-core/druid-basic-security) -> org.apache.druid:druid-services(druid/services)
org.apache.druid:druid-server(druid/server) -> org.apache.druid:druid-console(druid/web-console)
</code></pre>

After clean up, the build time has been reduced by **3min7s** when I use parallel build during Github Actions. 
Thread usage after cleaning up module dependencies was this:
![2](https://user-images.githubusercontent.com/92497220/165312828-3c5a6f58-09ee-4811-8686-8e9bf7a587d8.jpg)

Could you help me review this issue? I can submit a PR to improve build performance of the project.

Thank you very much for your attention.
Best regards.

**Comment by 2bethere** [comment]
What's the before time? And yes please if you can submit a PR it'll be great!

**Comment by FrankChen021** [comment]
A PR is welcomed. 

And what's the rationale that speeds up the build time? I'm curious that which tool are you using to get the thread usage during building.

**Comment by FrankChen021** [comment]
I'm wondering if we can make some chanes to current dependency check so that these dependency problems can be exposed earlier at least at the CI phase.

Druid's root pom contains dependency plugin declaration, but only these modules configure to use dependency check
<img width="624" alt="image" src="https://user-images.githubusercontent.com/6525742/165521083-8aa08793-64be-4645-bbe4-edfe885c9678.png">

So, it's better to enable the dependency check at the root pom level so that we don't need to configure it for each module.

**Comment by MC-JY** [comment]
Yes, t's better to enable the dependency check at the root pom level. This can improve maintainability
