### ISSUE TITLE
Druid web console in in 'No SQL mode'

### ISSUE THREAD

**Issue by soumyajose0784** [apache/druid#12688]
We have druid 0.22.1 deployed in on premise kubernetes cluster which works perfect. But deploying the same image to IT namespace results in druid router console running in 'No SQL mode'. Both environments use same configuration with difference only in names, metadata db and pvc mountpoints. I see no error in any of pod logs. Could I get some guidance.

**Comment by vogievetsky** [comment]
This can happen if the management proxy is not enabled in the router https://druid.apache.org/docs/latest/design/router.html#router-as-management-proxy

In Druid 24.0 there is a way to force the console to un-restrict.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/177816/205183167-f151001d-a8b4-4b85-b78e-154abc11fbc4.png">

Also there was a bug fixed in 24.0 that would have too short of a timeout on the capability detection. It should be a lot more robust now. Please reopen if you see this again.
