### ISSUE TITLE
A Bitmap Plug-in

### ISSUE THREAD

**Issue by libingxin** [apache/druid#12734]
In mobile advertising, there are a large number of advertising events every day. 
In order to analyze the effect of advertising promotion, we will analyze:

1. Daily clicks and impressions
2. User registrations of one app
3. UV, seven-day retention 
4. Multi-dimensional analysis, such as the distribution of people using different mobile phones

We use Druid to analyze，Druid is an excellent OLAP databas，most of the metrics such as daily clicks, registration, and UV are no problem 
But the  seven-day retention or multi-dimensional analysis metrics,  it is difficult to analysis.
So I want to write a Druid plug-in,  using bitmap to analysis user seven-day retention and other multi-dimensional. 

The feature:
1. Metric: bitmap，store different user or device id(int type)
2. Post-aggregator：bitmap‘s cardinality
3. Post-aggregator：operation and between bitmaps
4. Post-aggregator：operation or between bitmaps
5. Post-aggregator：operation xor between bitmaps

**Comment by FrankChen021** [comment]
Good proposal. Two questions:
1. Is this bitmap going to support rollup during ingestion?
2. Is roaringbitmap is used as the underlying data structure for this bitmap?

**Comment by libingxin** [comment]
1. Support Data ingestion such as kafka 
2. Use roaringbitmap,  roaringbitmap deserialize and serialize fast, less storage space

**Comment by FrankChen021** [comment]
Calculating cardinality in short time on large volume data is challengeable. We had similar implementation based on roaringbitmap too, but the problem is even the serialization & deserialization of roaringbitmap is fast enough, they're still bottleneck when calculating high cardinality data. 

Another problem is during query there will be too many bitmap object creation which will put heavy load on garbage collection.

So, I'm more care about the performance of such implementation. Do you have any reports that can be shared with us?
