### ISSUE TITLE
KafkaEmitter for request emitting does not emit "queryType" for native queries

### ISSUE THREAD

**Issue by BartMiki** [apache/druid#12912]
### Affected Version

The Druid version where the problem was encountered: `0.22.x`, `0.23.x`

### Description

When setting up a request emitter to use KafkaEmitter the `queryType` property is not serialized to a JSON. The problem is located in the method: `public void emit(final Event event)` of `KafkaEmitter.java`.

The problem is that the rendering of the JSON string is done on the `Map<String, Object>`. The Jackson ignores the polymorphic annotation on the Query class with `queryType` if the query is serialized as a part of the map (see: `DefaultRequestLogEvent` for explanation). If we serialize the query independently then the polymorphic annotation is respected.

### Proposed solution

The simples solution is to serialize an object to JsonNode first. If the `query` is present, then serialize it independently and replace the non-polymorphic version in the JsonNode.

**Comment by rohangarg** [comment]
@BartMiki : Thanks a lot for reporting the issue! I tried it locally in unit-tests and was able to reproduce it. The root cause as you mentioned, is related to missing of type information while doing jackson seriallziation for polymorphic types in maps/arrays.
The solution you proposed sounds good to me conceptually. Maybe instead of just serializing `query` independently, it could also be checked if we can do independent serializing of all KV pair in the map and then recombine all the KV jsons.

It would be great if you are also interested in contributing the fix patch to the main line!

**Comment by BartMiki** [comment]
@rohangarg Thank you for the response! I'm interested in contributing, actually, I already fix the issue on my fork. I will link the PR to this Issue once I finish the unit tests. I like your idea to parse each KV pair individually, I'll do that.

**Comment by FrankChen021** [comment]
I'm wondering if there's any public method provided by jackson to allow us to keep the annotation on objects which are stored in Map or Array?

Serializing  objects to JsonNode first and then serializing these JsonNodes into string, I'm worry about the performance of these two phase serialization.

**Comment by BartMiki** [comment]
Regarding Jackson, there is no such method. The problem occurs due to type erasure of generic classes (see this [ticket](https://github.com/FasterXML/jackson-databind/issues/699#issuecomment-73382972)).

Regarding the two-step serialization, I suggested a solution in the [PR comment](https://github.com/apache/druid/pull/12915#issuecomment-1219105113). The problem is that `KafkaEmitter` adds an additional property to the output event which complicates serialization a bit.

**Comment by rohangarg** [comment]
Thanks @FrankChen021 and @BartMiki for the thorough discussion. I have a few more points related to discussions : 
1. Regarding performance, I think we can check once the time taken for old vs new approach to prepare the event to see we're not adding a lot of time in absolute terms atleast.
2. Regarding the problem for compatibility arising b/w serializing using annotation vs using `asMap` method and then serializing, it seems like that should be solved. Otherwise, the kind of JSON created for the same event object would differ according to the implementation of the `Emitter` as it is happening now. We could call out the incompat in release notes if needed.
What do you think?

**Comment by BartMiki** [comment]
@rohangarg  regarding your points:

1. Do you have any tips how to measure that? Any recommended profilers? Maybe just a unit test per serialization method that runs serialization in a loop 100k times?
2. Current fix is compatible with previous output so there is no need for `incompat`. Actually it is interesting issue in general, because what is **the** method for generating output for the event? What is recommended by the Druid? Serialize Event with Jackson or with `.toMap`? To `.toMap` is part of Event which seems to be default, but many core Druid emitters just use Jackson on the Event. If somebody implements new emitter what they would default to? Maybe that should be included in the docs? To be honest I don't have a solution for that at this moment. Maybe we should introduce something like `EventToXSerializer` interfaces where `X` is format name. Then we can also provide default implementations, like `DefaultObjectMapper` is provided. What do you think? But that should be part of a new issue.

**Comment by FrankChen021** [comment]
If we want to fix the problem from root, I think we need to make changes to Event interface to make the special serialization process to be unvisible to callers.

My suggestion is as follows

```java

public interface Event {
    CustomerMap toMap();
    ...
}

class ACustomerMap extends HashMap<String, Object> {

     // a dedicated method to serialize this object into JSON string to avoid missing type info in the final text
     public String toJSONString() {
     }
}

```

Since `ACustomerMap` inherits Map<String, Object>, it makes current code where this method is called compatible with this new class.

**Comment by BartMiki** [comment]
Regarding the performance, I think there are no big differences. I made these test for both:
Old implementation:
```java
  public void testOldCode() throws JsonProcessingException {
    ObjectMapper mapper = new DefaultObjectMapper();
    Event event = getEvent();

    for (int i = 0; i < LOOP_COUNT; i++) {
      ImmutableMap.Builder<String, Object> resultBuilder = ImmutableMap.<String, Object>builder().putAll(event.toMap());
      if (CLUSTER_NAME != null) {
        resultBuilder.put("clusterName", CLUSTER_NAME);
      }
      Map<String, Object> result = resultBuilder.build();
      String resultJson = mapper.writeValueAsString(result);
    }
  }
```
New implementation:
```java
  public void testMyCode() throws JsonProcessingException
  {
    ObjectMapper mapper = new DefaultObjectMapper();
    Event event = getEvent();

    for (int i = 0; i < LOOP_COUNT; i++) {
      EventToJsonSerializer serializer = EventToJsonSerializer.of(mapper).withProperty("clusterName", CLUSTER_NAME);
      String actual = serializer.serialize(event);
    }
  }
```

I set up LOOP_COUNT to 100K. The results differ between the runs slightly, but these are the results (from IntelliJ):
![image](https://user-images.githubusercontent.com/29756184/185738942-8adbf692-29f8-4ca6-bed6-91f7329f462a.png)
Sometimes my code is slower:
![image](https://user-images.githubusercontent.com/29756184/185738989-86428299-cfca-4cf1-a4cc-4cf1cee11977.png)

I think that 100K is enough for the JIT to warm up. I guess the performance is comparable and it shouldn't be an issue.

**Comment by BartMiki** [comment]
@rohangarg I don't have any strong opinion regarding the compatibility. To be honest either way works for me. However, I support standardization. If all other emitters that serialize to JSON have all fields like: `query`, `sql` and `sqlQueryCtx` then I guess Kafka should have it too (or maybe it can be part of the configuration for the emitter). I would leave the decision to you @FrankChen021  and @rohangarg .

**Comment by BartMiki** [comment]
@FrankChen021 Regarding the changes to the Event I wonder if that is the best approach. My take is that `ACustomerMap` shouldn't be responsible for serialization. If we want to support more formats (le'ts say Avro, XML, Protobuf etc) then we need to extend this `ACustomerMap`. Maybe something like this?

```java
public abstract class EventSerializer<T> {
  public T serialize(Event event) {
    return serialize(event, Collections.emptyMap());
  }
  
  public abstract T serialize(Event event, Map<String, Object> additionalProperties);
}
``` 
And then we can have for example:
```
public class EventToJsonStringSerializer implements EventSerializer<String> { ... }

public class EventToXMLStringSerializer implements EventSerializer<String> { ... }

public class EventToObjectNodeSerializer implements EventSerializer<ObjectNode> { ... }

public class EventToByteArraySerializer implements Event<byte[]> {...}
```

So the users can use the provided serializers and the serializers can use the `toMap` or whatever else regarding the event. The upshot is that we have unified interface for serializing events to anything and the implementation always is in a single class. The downside is the change affects all emitters.

**Comment by FrankChen021** [comment]
Hi @BartMiki 

My point is, since this is a special case caused by jackson, we need to try hide these special treatment from users. 

If we provide an extra API to serialize the object returned by `toMap()` instead of using ObjectMapper directly,  every caller has to know there's such API provided, and they have to read some document to make sure they're using the right way to serialize, and they also may dive into the detail of such API to know why such API is provided. 
That's a burden for users.

A better suggestion is using customer serializer mechanism provided by jackson.

```java
public interface Event {
    EventMap toMap();
    ...
}

@JsonSerialize(using = ACustomerMapSerializer.class)
class EventMap extends HashMap<String, Object> {

}


public class EventMapSerializer extends JsonSerializer<EventMap>
{
  @Override
  public void serialize(
      EventMap value,
      JsonGenerator jgen,
      SerializerProvider provider) throws IOException
  {
      // do serialization
  }

  @Override
  public Class<EventMap> handledType()
  {
    return EventMap.class;
  }
}
```

By using such mechansim, user can serialize `ACustomerMap` directly by using `ObjectMapper`. 
And in the implementation of  `ACustomerMapSerializer.serialize`, I think there won't be two phase serialization as implemented in current PR.

**Comment by FrankChen021** [comment]
By the way, I'm not saying you have to deal with this problem in your PR if you don't have enough energy. I can merge that PR and do the things left. But if you want to make the improvement better, I appreciate it. @BartMiki

**Comment by BartMiki** [comment]
I want to contribute, let's do this properly!

**Comment by BartMiki** [comment]
It won't work like this, I need to update every override:
```java
  @Override
  @JsonValue
  public Map<String, Object> toMap() {}
```
because of error: `org.apache.druid.java.util.emitter.service.ServiceMetricEvent is not abstract and does not override abstract method toMap() in org.apache.druid.java.util.emitter.core.Event`

Any suggestions for a workaround @FrankChen021 ? Also, lots of implementation uses ImmutableMap, which is not a HashMap, so this is a bit more tricky to pull off.

**Comment by FrankChen021** [comment]
Hi @BartMiki 

Changing the signature of `toMap` does require to change all subclasses of `Event` interfaces. It's acceptable in this case.

I don't think the `EventMap` needs to be immutable because it does not hold any reference to original Event object it self. The reason immutable map is used I think is because it provides a builder pattern so that we can build a map object in chain.
which simplifies the coding. To make code change simpler, we can provide a builder pattern against `EventMap`.

**Comment by BartMiki** [comment]
@FrankChen021 I've updated the code with `EventMap`. Can you have a look?
