### ISSUE TITLE
Add Kafka hash partition type to improve query performance

### ISSUE THREAD

**Issue by 599166320** [apache/druid#12929]
### Motivation

We use druid to store a large amount of monitoring data. By default, the Kafka index service is used to ingest data, and the query performance is very poor.

After analysis, by default, the monitoring data will be randomly written into each partition of Kafka. The data will be randomly consumed by Kafka peon, and the index will be established to generate segments.

When querying, the broker can only filter segments by time, and cannot further filter according to query conditions. It needs to scan a large number of real-time nodes, historical nodes, and a large number of segments, resulting in poor performance.

### Proposed changes

1. Kafka real-time index service supports a new partition type, adding `KafkaPartitionNumberedShardSpec` class, which extents from `NumberedShardSpec` ,Override the `possibleInDomain` function in the `KafkaPartitionNumberedShardSpec` class, implement hash filtering, and add the following core fields:`type = "kafka_partition", kafkapartitionids, partitiondimensions`.

2. Modify the `KafkaIndexTask` class to support the `KafkaPartitionNumberedShardSpec` type in `kafkaindextask.newdriver`.

3. Add the `partitionfunction` field in the configuration of Kafka ingression spec, and configure all fields that need to be hashed in the `partitionfunction`.

4.  Add a simple hash code to the data production side:

```
int p = hash(dim1,dim2,...)
ProducerRecord<byte[], byte[]>(topic, p,event)
```

### Rationale
When writing data, partition the data, which is beneficial to compression and sorting. During the query, the scanning range is further trimmed by the user-defined filter conditions to optimize the performance of concurrent queries.

### Performance comparison

Before optimization
![FQrxkz62dz](https://user-images.githubusercontent.com/3204398/185734896-9555b9ae-5e08-44b6-8524-3da42cf35936.jpg)

After optimization
![A93J4pk1Qm](https://user-images.githubusercontent.com/3204398/185734907-d3c111d0-fb45-4bd7-9442-16e6e786e001.jpg)

**Comment by gianm** [comment]
This kind of approach is definitely great for performance. The main reason we haven't done it yet is that it can be too fiddly for most users. A key problem is: what happens if the producer doesn't correctly do the hash codes? What if we want to add partitions to the kafka topic? We would want to build something that the average user could use easily, and correctly.

Something I had thought of in the past, but never implemented, was to do something like you suggest, but add an extra safety step that detects if partitioning has been done correctly by the kafka producer. If it has, then we write shard specs that are pruneable; otherwise we write ones that are not pruneable. Another option would be to use Bloom filters for pruning rather than hash function, that way we are flexible to whatever way data has been partitioned by the producer. Bloom filters could be too big to stuff into a shard spec, though.

I'm wondering if you have thoughts around how this could be done in a way that is robust to the user doing partitioning "wrong", adding partitions, etc?

Btw, I'm not sure if you are doing this already, but after handoff you can use reindexing / compaction to rewrite data with `range` partitioning and get pruneable shard specs. We do this in production for some datasources that originate from Kafka.

**Comment by 599166320** [comment]
> 


thank you for your reply。

In fact, we have used this technology in large-scale clusters and have seen better query performance.

Our implementation may be more complicated than I have described. In a table, we use not only hash partitions but also enumeration partitions, considering data skew and combining hash partitions.

I also want to talk about my own views on some of the issues you mentioned above.

1. what happens if the producer doesn't correctly do the hash codes?

I think we can implement something similar to the client SDK to constrain this behavior. The Kafka header carries some partition information, indicating that the producer writes data according to the specification.


2. What if we want to add partitions to the kafka topic?

The Kafka producer can specify to write the existing partition. Even if the partition is added, the old partition can still be written. In most cases, the partition of Kafka topic only allows capacity expansion, not capacity reduction.

Because it is very expensive to delete the topic, the volume will not be reduced by deleting the topic.


3. We would want to build something that the average user could use easily, and correctly.

I think that average users prefer to configure their tables step by step through the browser interface in the existing way, so there will be no mental burden.

If Druid can provide the implementation of Kafka partition type at the database level, many developers do not need to implement and maintain these nonstandard codes, and can unlock more performance.
