### ISSUE TITLE
Modify scanQuery to support orderby

### ISSUE THREAD

**Issue by 599166320** [apache/druid#12958]
### Motivation

We are looking forward to using Druid's scanQuery to do the order by operation, but so far, Druid has no corresponding version support.

To use orderby, we can only use groupbyquery / topnquery.

However, We are not satisfied with the performance of groupByQuery. Using topn to implement, the performance will be better, but there are limitations. It can only be one-dimensional.

We support the orderby algorithm of scanquery.

Mainly to modify the scanQueryEngine，ScanQueryRunnerFactory class,

I don't know if anyone has tried this before. What problems will encounter?

Step 1: extract the column to be sorted and the corresponding offset, and store the column to be sorted and the offset value of topn in the MultiColumnSorter. The column to be sorted is the key and the offset is the value

Step 2: extract relevant rows according to the offset of MultiColumnSorter and generate the final topn return.

**Comment by gianm** [comment]
The approach makes sense to me. There would be a couple of limitations:

- We would have to scan the entire dataset (everything matching the filter), since unlike with time-ordered scan, the data is not already pre-ordered.
- We would need to require a limit be set to some reasonable value. If the limit is too high then servers would run out of memory.

Btw, the code added in #12848 (SuperSorter) and #12918 (multi-stage query task) actually does support Scan with ORDER BY and disk-based sorting (so limit can be very high, restrained only by available disk space). But the approach you describe would be better for smaller limits, since it's all in memory, and would be more efficient.

Would you be interested in implementing this?

**Comment by 599166320** [comment]
> The approach makes sense to me. There would be a couple of limitations:
> 
> * We would have to scan the entire dataset (everything matching the filter), since unlike with time-ordered scan, the data is not already pre-ordered.
> * We would need to require a limit be set to some reasonable value. If the limit is too high then servers would run out of memory.
> 
> Btw, the code added in #12848 (SuperSorter) and #12918 (multi-stage query task) actually does support Scan with ORDER BY and disk-based sorting (so limit can be very high, restrained only by available disk space). But the approach you describe would be better for smaller limits, since it's all in memory, and would be more efficient.
> 
> Would you be interested in raising this as a PR?

Thank you for your reply! I'm interested in contributing。In fact, I have implemented the query of scanorderby。I will link the PR to this issue later
In addition, your ideas on sorting are very thoughtful.  (SuperSorter) and  (multi-stage query task)  look great. I can't wait to experience them。

**Comment by arksnr** [comment]
Can this be prioritized?
