### ISSUE TITLE
Warnigs in Druid node logs after upgrade Java to 11

### ISSUE THREAD

**Issue by themaric** [apache/druid#13216]
Hi guys,

Just to let you know (probably nothing, but just in case) that I've found some warnings being logged down each time Druid nodes are started:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/local/apache-druid-24.0.0/lib/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.securit
y.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Thanks and keep up the great job!

**Comment by FrankChen021** [comment]
It's a known problem. See: https://github.com/apache/druid/pull/12232#issuecomment-1059917494

This won't cause any problem as I know. I don't know there is somebody working on this problem because it's a little bit tricky.

**Comment by gianm** [comment]
This is due to JDK encapsulation: https://druid.apache.org/docs/latest/operations/java.html#strong-encapsulation

You can avoid them, if you like, by adding the mentioned `--add-exports` and `--add-opens` to your jvm parameters. Although as mentioned, the warnings are harmless, so this isn't required. Patch #12839 adds some logic to the startup scripts to set these automatically on Java 17, where they _are_ required.

**Comment by gianm** [comment]
Closing since this is not an issue on Java 11, and on Java 17 we set the required parameters in the startup scripts. Please let us know if you run into problems.
