### ISSUE TITLE
The version 24 did not load the task logs from 0.23.0 when upgraded

### ISSUE THREAD

**Issue by junwansas** [apache/druid#13232]
The version 24 did not load the task logs from 0.23.0 when upgraded

### Affected Version

24

### Description

Please include as much detailed information about the problem as possible.
- Cluster size: Single machine installation
- Configurations in use: xlarge
- Steps to reproduce the problem: create some kafka ingestion tasks in version 0.23.0. Let them run sometime to create task logs. Upgrade in place to version 24. The tasks logs disappeared from web console.
- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful. There is no error massage on the web console. 
- Any debugging that you have already done: No

**Comment by gianm** [comment]
Hi @junwansas, thanks for your report!

I just tried this locally, and task logs stayed present when upgrading from 0.23.0 to 24.0.0. I did the following steps:

- Unzip `apache-druid-0.23.0-bin.tar.gz`
- Run the Kafka tutorial: https://druid.apache.org/docs/0.23.0/tutorials/tutorial-kafka.html
- Stop the Apache Druid 0.23.0 services
- Unzip `apache-druid-24.0.0-bin.tar.gz`
- Move `var` directory from `apache-druid-0.23.0` to `apache-druid-24.0.0`
- Run `bin/start-micro-quickstart` from the Druid 24.0.0 directory
- Check web console for logs

It is possible that you did not move over the `var` directory. This part is important since a bunch of stuff is stored there, like task logs.

If you have any further issues please do not hesitate to reopen this.

**Comment by junwansas** [comment]
Question: is that possible to config the system so that the task logs stored out side of var in a network location so that we do not need move this?

Thank you!

Jun Wan
Enterprise Data Platform Services
O 404.269.6804
C 404.625.2056
6305 Peachtree Dunwoody Rd. Atlanta, GA 30328



From: Gian Merlino ***@***.***>
Sent: Monday, November 21, 2022 12:07 AM
To: apache/druid ***@***.***>
Cc: Wan, Jun (CCI-Atlanta) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [apache/druid] The version 24 did not load the task logs from 0.23.0 when upgraded (Issue #13232)

Hi @junwansas, thanks for your report! I just tried this locally, and task logs stayed present when upgrading from 0. 23. 0 to 24. 0. 0. I did the following steps: Unzip apache-druid-0. 23. 0-bin. tar. gz Run the Kafka tutorial: https: //druid. apache. org/docs/0. 23. 0/tutorials/tutorial-kafka. html


Hi @junwansas<https://urldefense.com/v3/__https:/github.com/junwansas__;!!Hit2Ag!0joRKJwoatDt57BxNx3GzPebexM1A3GuM8cuoClqSRsGR112FJwDb2EOV8UgUvzoZRidNoGZpe0aQdIqWp0Rwg$>, thanks for your report!

I just tried this locally, and task logs stayed present when upgrading from 0.23.0 to 24.0.0. I did the following steps:

  *   Unzip apache-druid-0.23.0-bin.tar.gz
  *   Run the Kafka tutorial: https://druid.apache.org/docs/0.23.0/tutorials/tutorial-kafka.html<https://urldefense.com/v3/__https:/druid.apache.org/docs/0.23.0/tutorials/tutorial-kafka.html__;!!Hit2Ag!0joRKJwoatDt57BxNx3GzPebexM1A3GuM8cuoClqSRsGR112FJwDb2EOV8UgUvzoZRidNoGZpe0aQdI32WSdUg$>
  *   Stop the Apache Druid 0.23.0 services
  *   Unzip apache-druid-24.0.0-bin.tar.gz
  *   Move var directory from apache-druid-0.23.0 to apache-druid-24.0.0
  *   Run bin/start-micro-quickstart from the Druid 24.0.0 directory
  *   Check web console for logs

It is possible that you did not move over the var directory. This part is important since a bunch of stuff is stored there, like task logs.

If you have any further issues please do not hesitate to reopen this.
