### ISSUE TITLE
Druid query to get last N transactions from the db

### ISSUE THREAD

**Issue by cisco2825** [apache/druid#14914]
I have written a druid topN query to fetch the last n transactions performed from the db. I have aggregated __time column and used it as the metric for the topN query.  For aggregation I have used longLast aggregator.

But this query is taking too much time in case of multiple segment data. Can someone please suggest me what optimization I can do in the query to make it faster.  Or if there is some other faster way to  get the last n transactions.

Adding the structure of the query I have:

{
      "dataSource": {
        "type": "table",
        "name": "txn"
      },
      "queryType": "topN",
      "intervals": [
        "2021-08-24T15:51:54.599+05:30/2023-08-24T10:21:54.599Z"
      ],
      "granularity": "all",
      "virtualColumns": [
        {
          "type": "expression",
          "name": "sourceValue",
          "outputType": "STRING",
          "expression": "regexp_extract(trim(transEntityRecords), '(.*)attributeID(.*)909075081867,.values.:(..([-0-9]*(.[-0-9]+)?))(.*)', 4)"
        }
      ],
      "filter": {
        "type": "and",
        "fields": [
          {
            "type": "in",
            "dimension": "gsiId",
            "values": [
              "1595974428413"
            ]
          },
          {
            "type": "in",
            "dimension": "triggerCuId",
            "values": [
              "1240994321229"
            ]
          },
          {
            "type": "selector",
            "dimension": "triggerState",
            "value": "COMPLETED"
          },
          {
            "type": "or",
            "fields": [
              {
                "type": "selector",
                "dimension": "gsiName",
                "value": "MaxLimitLoadTestingGSI"
              },
              {
                "type": "selector",
                "dimension": "cuName",
                "value": "test CU27281"
              },
              {
                "type": "selector",
                "dimension": "cuIndex",
                "value": "1"
              },
              {
                "type": "selector",
                "dimension": "txnSlotItemDataName",
                "value": "NumberEntity 862"
              }
            ]
          }
        ]
      },
      "aggregations": [
        {
          "type": "count",
          "name": "count"
        },
        {
          "type": "doubleLast",
          "name": "sourceValue",
          "fieldName": "sourceValue"
        },
        {
          "type": "longLast",
          "name": "time",
          "fieldName": "__time"
        }
      ],
      "dimension": {
        "type": "default",
        "dimension": "transactionId",
        "outputName": "transactionId",
        "outputType": "STRING"
      },
      "threshold": 38211,
      "metric": "time"
    }

NOTE: 
1) Interval is supposed to be 2 years. So can not reduce that
2) All the filters/virtual columns are essentials

**Comment by cisco2825** [comment]
@petermarshallio @tijoparacka @abhishekagarwal87 
Can anyone please help on this.

**Comment by renatocron** [comment]
Hello!

2 years is potentially a lot of segments that need to be scanned, so you are missing one of the main advantage of having a primary index based on time, if you ask the database to scan all the segments all the time.

There are a few options to consider:

You can try turn cache on on the historical nodes (no on the broker, caching on the broker would not matter for this query), that could help if you don't have any late arriving data and reserve a some RAM for caching, both on historicals node RAM as well on the historical: https://druid.apache.org/docs/latest/configuration/#historical-caching

But I'm afraid druid can't otimize `longLast`, because it may need to scan all the matched segments to send to the broker to compare which is the overall latest.

You can consider make a external Service / Application:

This service could be configured to read data from the same ingestion sources and update a separate, faster storage system (like Redis, DuckDB or an in-memory database).

Here's a simple outline of how you could design it:

- The service reads from the same ingestion source that Druid uses.
- It updates a faster storage (like Redis).
- The structures stored in this faster database mirror those in Druid.
- You query the faster storage directly for the most recent transactions.
- If this fails, you fall back to querying Druid.
- This system would also rely on Druid as a source of truth, when your application boots up or if the in-memory database fails.
This approach frees you from sending each query to Druid and allows you to retrieve the most recent transactions much more quickly. It does, however, require this additional service to be maintained.

Nevertheless, you could also check if the segment compaction are optimized for your needs:

Segments Optimization (Secondary Indexing): If your data has some natural order or frequently queried fields, you could specify secondary indexes using autocompaction with range, for example [https://druid.apache.org/docs/latest/ingestion/native-batch#benefits-of-range-partitioning](https://druid.apache.org/docs/latest/ingestion/native-batch#benefits-of-range-partitioning). Although time-based partitions are the primary indexing method in Druid, secondary indexes could help improve query latency by reducing the quantity of data that needs to be scanned, maybe you can have segments just with the triggerState=COMPLETED in one place, or create a new datasource just for them
