### ISSUE TITLE
Changing the queryFrameWork in Calcite*Tests may have sideeffects

### ISSUE THREAD

**Issue by kgyrtkirk** [apache/druid#15427]
the method named `requireMergeBuffers(1)` ; changes the field `queryFramework` which may change the behaviour of later testcases

adding this testcase to `CalciteQueryTest` creates 2 failing tests
```java
  @Test
  public void testMergeBufferSettingHasSideEffect() {
    requireMergeBuffers(1);
  }
```

**Comment by LakshSingla** [comment]
I have seen this issue. I attempted to solve it but the way merge buffers are wired, I wasn't able to find a simple fix for the same - I was able to create a new framework per test (which isn't ideal as it increased the test time by 10x) 

I attempted to cache the num merge buffers currently being used, reset that int per test, and check the last test's merge buffers (we cached), and if the two mismatched, then call requireMergeBuffers(..) again. This would cause the merge buffers to increase when we call the requireMergeBuffers(..) code, and reset back to 0 the next test until we call it back again explicitly. 
However, it didn't work as expected because of how the test framework was written.
