### ISSUE TITLE
Error while running mvn build 

### ISSUE THREAD

**Issue by Shekharrajak** [apache/druid#17375]
I run this in main branch : 

```
mvn clean install -Papache-release,dist,rat -DskipTests -Dgpg.skip -Ddependency-check.skip=true
```

and getting this error: 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.1:jar (attach-javadocs) on project grpc-query: MavenReportException: Error while creating archive: 
[ERROR] Exit code: 1 - /Users/druid/extensions-contrib/grpc-query/target/generated-sources/protobuf/grpc-java/org/apache/druid/grpc/proto/HealthGrpc.java:7: error: cannot find symbol
[ERROR] @javax.annotation.Generated(
```

Please let me know if someone is aware of it.

**Comment by abhishekrb19** [comment]
Closing this issue as it was resolved in this Slack thread -https://apachedruidworkspace.slack.com/archives/C030CMF6B70/p1729298086288679.

The gist of the issue was the use of maven profile `rat` with `-Ddependency-check.skip`.  On a related note, it would be worthwhile updating the page https://druid.apache.org/docs/latest/development/build/ with maven options that folks use for development these days.
