### ISSUE TITLE
[Proposal] Throttling for segment loading in druid coordinator

### ISSUE THREAD

**Issue by nishantmonu51** [apache/druid#2966]
Scenario - In our metrics cluster, we keep super old data on icy tier without any replication, where we have ~15K+ segments on a single historical node, which accounts to ~ 20K segments on single node. When we reboot these beefy historical nodes, the coordinator tries to load all the segments present on that node onto other available nodes. Since the number of segments is too high, it takes around 4-5 hours for the coordinator to complete single iteration over all the segments while computing cost and finding the best server to load those segments . This delays segment handoff as the coordinator takes snapshot of available segments and iterates over those segments. 

As per the current implementation we have a replication throttling limit only while segments are being replicated in the cluster, but since we don't have replication configured for the data in icy tier, the replication throttling does not helps in this case. 

The proposal is to add another throttling limit for segments loaded in each tier which would define the maximum number of new segments that the coordinator will try to load in a tier at one time. 

Implementation would include - 
- Adding loadingThrottleLimit to coordinator dynamic config 
- Modifying loadRule to follow this limit while loading new segments to a tier
- proposed Default value for loadingThrottleLimit is 5000. (Its high in order to not alter any existing behavior by default)

**Comment by fjy** [comment]
I think in general this proposal makes sense but the loadingThrottleLimit should be unlimited by default to keep with the current impl of things.

**Comment by drcrallen** [comment]
@fjy if default behavior breaks or has bad side effects over a certain size, it is not clear to me we should keep it.

**Comment by sascha-coenen** [comment]
highly useful and needed feature !!

Speaking about dynamic coordinator configs, there are two further things that would allow for handling many useful usecases:
* having the dynamic configs per tier
* being able to set a tier's priority dynamically in the coordinator

If something like this is doable and considered reasonable, I would like to create a feature request for this too.

**Comment by sascha-coenen** [comment]
I don't understand why this proposal hasn't been taken up yet. I've been running a large scale Druid cluster and the use case  that nishantmonu51 described in his proposal is a real one and it can cause really big issues. 

I haven't been working with Druid in recent years. If the issue raised by nishantmonu51 has become void because of some other feature or change introduced to Druid, then it might make sense to close the issue, but in this case I would appreciate it, if a short comment could be added in here as to how to resolve the stated issue. 

If the issue described in the proposal is still valid, I highly recommend to re-open this ticket and prioritise it, as the implementation would be a small effort having a high impact.
