### ISSUE TITLE
Consider including hadoop-aws in the lib folder

### ISSUE THREAD

**Issue by priteshwatch** [apache/druid#3435]
https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws/2.6.0

S3 ingestion does not work without this library in the lib folder, as far as I can tell.

**Comment by moscowart** [comment]
One year later same issue. Is there any reason for that? It's just 123 Kb.

**Comment by wooly** [comment]
This appears to still be the case.

Can anyone shed any light on why it's not there?

**Comment by shaharck** [comment]
+1

**Comment by nishantmonu51** [comment]
this is still an issue

**Comment by nishantmonu51** [comment]
Stack trace when trying to use s3a 
```
2019-10-29T21:59:00,942 INFO [forking-task-runner-0] 
org.apache.druid.indexing.overlord.ForkingTaskRunner - Exception caught during execution
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2661) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3307) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3339) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:137) ~[?:?]
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3390) ~[?:?]
```

**Comment by jihoonson** [comment]
Is this a good idea? I think users should download the valid version of hadoop-aws.jar by themselves. They can use the pull-deps tool for it.

**Comment by gianm** [comment]
> Is this a good idea? I think users should download the valid version of hadoop-aws.jar by themselves. They can use the pull-deps tool for it.

Hmm, why not include it? We include the aws sdk in the s3 extensions bundled with Druid, it seems nice to include the hadoop version too.

**Comment by jihoonson** [comment]
> Hmm, why not include it? We include the aws sdk in the s3 extensions bundled with Druid, it seems nice to include the hadoop version too.

I think the packaged jars should be minimized and so include only mandatory ones. `hadoop-aws` is only useful when they want to deal with s3 via hdfs. It seems a sort of an extension of an extension to me.

**Comment by gianm** [comment]
> I think the packaged jars should be minimized and so include only mandatory ones. `hadoop-aws` is only useful when they want to deal with s3 via hdfs. It seems a sort of an extension of an extension to me.

Hmm, well, personally I think including it is nice, since it makes the app easier to use out of the box for AWS people and doesn't bloat the distribution too much. However, I would be ok not including it if we add something to the docs that says exactly what command to run to get `hadoop-aws` working properly. (These things are hard for users to figure out from first principles)

I'm ok with whatever y'all think is best (@jihoonson and @nishantmonu51) if you agree with each other. If not my vote goes to including the jar.

**Comment by jihoonson** [comment]
I think it makes more sense to add to docs as for GCS (https://druid.apache.org/docs/latest/development/extensions-core/hdfs.html).

**Comment by ccaominh** [comment]
I think it'd also be good to include `hadoop-aws` by default to improve the user experience — especially since [the documentation for hadoop ingestion has examples that have paths in S3](https://druid.apache.org/docs/latest/ingestion/hadoop.html#inputspec).

I also agree that S3 docs should be added to the HDFS page.

**Comment by jihoonson** [comment]
> I think it'd also be good to include `hadoop-aws` by default to improve the user experience — especially since [the documentation for hadoop ingestion has examples that have paths in S3](https://druid.apache.org/docs/latest/ingestion/hadoop.html#inputspec).

Particularly for the hadoop doc linked, I think the doc is wrong. The example should use `hdfs` instead of `s3n`.

I don't see much benefit for including `hadoop-aws` in `lib`. Isn't it enough if we add a doc saying "you need hadoop-aws.jar in your classpath and here is how you can get it using the `pull-deps` tool"? We currently have no hadoop-related jars under `lib`. All of them are under `hadoop-dependencies` or `extensions/druid-hdfs-storage`. I guess it could be another option to include `hadoop-aws` in `druid-hdfs-storage`.

**Comment by ccaominh** [comment]
#8782 proposes adding `hadoop-aws` to `extensions/druid-hdfs-storage`.

**Comment by jnaous** [comment]
+1 for adding libs by default. People always seem to stumble on missing
libs. It would be great to remove setup steps from documentation and making
more things "work OOB" as much as possible.

**Comment by jihoonson** [comment]
Oh sorry my bad. #8782 sounds good to me then.

**Comment by maytasm3** [comment]
+1 for adding lib. Adding hadoop-aws and gcs lib manually to get things to work is not user friendly. Also more error prone (where to add the lib to, what version, if class path is included, etc.(
