### ISSUE TITLE
Store bitmap sizes along with bitmaps in the segment format

### ISSUE THREAD

**Issue by leventov** [apache/druid#3882]
Absence of precomputed bitmap sizes makes implementation of features like #3878 and #3848 much less effective than it could be.

**Comment by gianm** [comment]
One thing to be careful of here is that 4 bytes per bitmap can add up quickly for high cardinality dimensions. Still a useful idea though.

**Comment by leventov** [comment]
@gianm we can use condensed integer encodings, where the highest bit of each byte is a continuation flag. Number 0-127 take just 1 byte.

**Comment by gianm** [comment]
yes, for sure that is a valid approach. Just wanting to make sure that this issue is considered. It may also be worth while to skip the size field for small bitmaps where computing size is fast. Odds are, high cardinality dimensions will generally have small bitmaps. I'm not sure though since I'm not sure of the speed difference between reading a vsize int and computing size for a small bitmap.
