### ISSUE TITLE
Better long and float column compression

### ISSUE THREAD

**Issue by leventov** [apache/druid#4080]
The idea is brought here: https://github.com/druid-io/druid/issues/4027#issuecomment-285482520

https://github.com/lemire/JavaFastPFOR

**Comment by leventov** [comment]
Also a good timeseries compression algorithm is described here: http://www.vldb.org/pvldb/vol8/p1816-teller.pdf

**Comment by leventov** [comment]
Also
https://lemire.me/blog/2017/09/27/stream-vbyte-breaking-new-speed-records-for-integer-compression/

**Comment by gianm** [comment]
I ran some benchmarks using JavaFastPFOR today and got the following sizes and timings. The dataset was ints with randomness uniformly distributed over some number of bits. I did three scans: at 10%, 95%, and 100% selectivity.

Some notes:

1. "uncompressed" means VSizeColumnarInts (byte packing). "compressed" means byte packing + LZ4 with blocksize of 64KB (however many byte-packed ints fit in). "fastPfor" means JavaFastPFOR with blocks of 16384 ints.
2. The FastPFOR implementation has an unnecessary copy on the decompression path: the library accepts compressed data as `int[]` but we really have `ByteBuffer`. So modifying the library to accept `ByteBuffer` should improve performance somewhat.
3. LZ4 was not able to compress this data. It got a little larger, indicating LZ4 probably just stored the data as-is, with some header indicating such. This wasn't surprising for random-bits settings close to a whole byte, since in that case it would have been trying to compress whole bytes of random bits. But I was surprised that it couldn't compress well with, for example, 11 random bits. 
4. FastPFOR did a good job compressing, especially on numbers of bits far from a whole byte. This makes sense since it does bit packing rather than byte packing. It always got the best data size.
5. FastPFOR beat the other schemes on scan rate of the whole dataset, by about 10–30%. On the 95% selectivity scan it was about even (seemingly mostly because of the added overhead of walking the filter bitset). On the 10% selectivity scan it performed the worst, about 70% slower. This is possibly because its work is amortized over fewer rows (the implementation must unpack an entire block of 16384 ints to get even one, whereas other implementations must LZ4-decompress the entire block, but only need to byte-unpack the specific rows being read). I would expect this all to improve somewhat if the unnecessary copy is eliminated.

```
Benchmark                                     (bits)  (filteredRowCount)   (rows)  Mode  Cnt      Score      Error  Units
CompressedColumnarIntsBenchmark.compressed         7              300000  3000000  avgt   20   2943.665 ±   68.762  us/op
CompressedColumnarIntsBenchmark.compressed         7             2850000  3000000  avgt   20  20766.045 ±  501.196  us/op
CompressedColumnarIntsBenchmark.compressed         7             3000000  3000000  avgt   20  15801.290 ±  349.125  us/op
CompressedColumnarIntsBenchmark.compressed        11              300000  3000000  avgt   20   3321.190 ±   74.982  us/op
CompressedColumnarIntsBenchmark.compressed        11             2850000  3000000  avgt   20  20621.893 ±  607.840  us/op
CompressedColumnarIntsBenchmark.compressed        11             3000000  3000000  avgt   20  14974.348 ±  450.959  us/op
CompressedColumnarIntsBenchmark.compressed        15              300000  3000000  avgt   20   3021.729 ±  103.790  us/op
CompressedColumnarIntsBenchmark.compressed        15             2850000  3000000  avgt   20  20802.272 ± 1672.917  us/op
CompressedColumnarIntsBenchmark.compressed        15             3000000  3000000  avgt   20  14651.987 ±  378.612  us/op
CompressedColumnarIntsBenchmark.compressed        21              300000  3000000  avgt   20   3706.261 ±  119.774  us/op
CompressedColumnarIntsBenchmark.compressed        21             2850000  3000000  avgt   20  23446.937 ±  716.861  us/op
CompressedColumnarIntsBenchmark.compressed        21             3000000  3000000  avgt   20  20023.993 ±  692.204  us/op
CompressedColumnarIntsBenchmark.fastPfor           7              300000  3000000  avgt   20   4882.731 ±  163.518  us/op
CompressedColumnarIntsBenchmark.fastPfor           7             2850000  3000000  avgt   20  21581.873 ±  646.544  us/op
CompressedColumnarIntsBenchmark.fastPfor           7             3000000  3000000  avgt   20  13632.693 ±  546.829  us/op
CompressedColumnarIntsBenchmark.fastPfor          11              300000  3000000  avgt   20   5583.134 ±  162.427  us/op
CompressedColumnarIntsBenchmark.fastPfor          11             2850000  3000000  avgt   20  21851.592 ±  861.589  us/op
CompressedColumnarIntsBenchmark.fastPfor          11             3000000  3000000  avgt   20  14563.488 ±  586.785  us/op
CompressedColumnarIntsBenchmark.fastPfor          15              300000  3000000  avgt   20   6340.217 ±  257.035  us/op
CompressedColumnarIntsBenchmark.fastPfor          15             2850000  3000000  avgt   20  23250.500 ± 1115.758  us/op
CompressedColumnarIntsBenchmark.fastPfor          15             3000000  3000000  avgt   20  14999.228 ± 1055.155  us/op
CompressedColumnarIntsBenchmark.fastPfor          21              300000  3000000  avgt   20   7450.851 ±  122.857  us/op
CompressedColumnarIntsBenchmark.fastPfor          21             2850000  3000000  avgt   20  24930.446 ±  621.486  us/op
CompressedColumnarIntsBenchmark.fastPfor          21             3000000  3000000  avgt   20  16123.002 ±  481.372  us/op
CompressedColumnarIntsBenchmark.uncompressed       7              300000  3000000  avgt   20   2837.838 ±   98.147  us/op
CompressedColumnarIntsBenchmark.uncompressed       7             2850000  3000000  avgt   20  22704.229 ±  885.314  us/op
CompressedColumnarIntsBenchmark.uncompressed       7             3000000  3000000  avgt   20  17371.661 ±  421.292  us/op
CompressedColumnarIntsBenchmark.uncompressed      11              300000  3000000  avgt   20   2889.088 ±   79.596  us/op
CompressedColumnarIntsBenchmark.uncompressed      11             2850000  3000000  avgt   20  23247.499 ±  606.357  us/op
CompressedColumnarIntsBenchmark.uncompressed      11             3000000  3000000  avgt   20  17543.058 ±  314.034  us/op
CompressedColumnarIntsBenchmark.uncompressed      15              300000  3000000  avgt   20   2845.691 ±   52.430  us/op
CompressedColumnarIntsBenchmark.uncompressed      15             2850000  3000000  avgt   20  22749.856 ±  707.239  us/op
CompressedColumnarIntsBenchmark.uncompressed      15             3000000  3000000  avgt   20  17000.533 ±  673.675  us/op
CompressedColumnarIntsBenchmark.uncompressed      21              300000  3000000  avgt   20   2951.205 ±  102.273  us/op
CompressedColumnarIntsBenchmark.uncompressed      21             2850000  3000000  avgt   20  22556.333 ± 1121.255  us/op
CompressedColumnarIntsBenchmark.uncompressed      21             3000000  3000000  avgt   20  16884.971 ±  357.128  us/op

7 bits:
compressed size = 3012020
uncompressed size = 3000009
fastPfor size = 2651425

11 bits:
compressed size = 6011812
uncompressed size = 6000008
fastPfor size = 4151509

15 bits:
compressed size = 6024346
uncompressed size = 6000008
fastPfor size = 5651525

21 bits:
compressed size = 9036750
uncompressed size = 9000007
fastPfor size = 7901473
```

**Comment by gianm** [comment]
Btw we already have implemented a better long (int64) compression about a year ago, although it is still off by default. It uses fixed length bit packing so it supports relatively random access. Maybe it's time to turn it on by default and disable LZ4 by default.

Some sizings and timings are in https://imply.io/post/2016/12/07/compressing-longs.html.

(Here, we did test more distributions, and found that for uniform distributions, bit packing of deltas compresses smaller than lz4; but for power law distributions lz4 is smaller. In all cases, bit packing is fastest, since the old implementation of int64 columns didn't even do byte packing).

**Comment by lemire** [comment]
@gianm 

I'm available and interested in helping out. 

Note: This could end up generating an interesting paper if you guys care about documenting the work. I'd love to help make this happen.

email: lemire@gmail.com

**Comment by gianm** [comment]
@lemire Thanks for the offer. At this point I have one main question: do you know if your JavaFastPFOR library is still the best freely-licensed, small-ish-integer compression library for Java that you are aware of? (I'm looking to compress the offset section of string columns; in Druid we expect these to be positive ints with the max value being the cardinality of the column -- which is never more than a few million and is often less.)

Another note: currently Druid can access values in int columns randomly, since we pack into a fixed number of bytes per value (whatever is needed based on the max value for the overall column). Random access isn't supported by JavaFastPFOR, and I suspect that contributes to its relative slowness on the 10% selectivity test. I would like to run some tests with fixed-length bit packing (which could support random access) to see how it fares on various selectivities vs. FastPFOR.

**Comment by gianm** [comment]
I edited the original comment to include BinaryPacking too (the paper says it's fixed-width bit packing). They look similar to FastPFOR at the current block sizes I'm testing.

**Comment by lemire** [comment]
In case you don't know about Upscaledb: https://upscaledb.com

cc @cruppstahl

**Comment by b-slim** [comment]
@gianm Am also wondering if we are taking advantage of the fact that the array of ints is sorted with known min and max, I guess that should help.

**Comment by gianm** [comment]
@b-slim Binary packing definitely takes advantage of the fact that the mins and maxes are known. I didn't pick encodings that take advantage of sortedness, however, because in general we can only expect at most one dimension's values to be sorted (the first one, and only if segmentGranularity = queryGranularity). In some cases this does happen and would be a useful optimization, but I wasn't worrying about it at this point.

`__time` we can always expect to be sorted, however it's int64 not int32 and I was only looking at int32 compression recently. But for `__time` I'm hoping we can switch the default to one of the strategies from https://imply.io/post/2016/12/07/compressing-longs.html soon. I'd expect both delta and table encoding should work very well on `__time` columns (table for coarse granularities and delta for fine ones).

**Comment by lemire** [comment]
Again... no interest in this? The potential is huge.

**Comment by clintropolis** [comment]
@lemire I am still very interested in pushing forward on this, and I agree with you on the implications. I've been stalling on making any progress on this issue or with my experiments until #6794 is merged, mainly because vectorization of the rest of the query processing engine changes the dynamics a bit at the compression layer and I want to make sure I am also targeting that optimally since I think it's probably the future of the query engine. But as soon as it goes in, I definitely plan to pick this back up!

**Comment by lemire** [comment]
Ok. Feel free to get in touch with me when you get to it, if you want.

**Comment by CmdrKeen** [comment]
@lemire @clintropolis  - I'm interested :) and #6794 is now merged also. Is there still an apitite to look into this?

**Comment by lemire** [comment]
@CmdrKeen I can't lead this, but I sure could help with pointers and reviews.

**Comment by clintropolis** [comment]
Hi @CmdrKeen,
Apologies in advance for the wall of text. 

#6016 captures much of my experiments and findings into this so far. For integer compression of dictionary encoded string columns, FastPFOR is a very solid improvement in many cases, but was not always better across the board for some value distributions. However the strategy taken in #6016, which uses it as part of an approach that attempts to find the "best" encoding for a given set of values at ingestion time, I feel has been at least proven as viable in that PR.

The main stalling point I ran into was when I wired up the C++ implementation of FastPFOR to Druid through JNI and ran into the situation where the C++ and Java implementations are not actually compatible (and don't claim to be, I was just experimenting to see if I could make it go faster). The performance increase of the C++ version make it worth using, but it is also necessary to have a fallback to pure java for cases when the compiled native version is not available for a platform. I also think the 'native' version of my branch in that PR is a bit cleaner of an implementation since it deals in bytebuffer/memory locations rather than on heap arrays like the branch associated with #6016 itself (see https://github.com/clintropolis/druid/compare/shapeshift...clintropolis:shapeshift-native for the jni branch differences). 

I've been intending to pick this back up for like... over a year now, but I just haven't been able to prioritize it to bring it to the finish line. I did "dust off" the branches and start testing stuff a few months ago, but haven't pushed my changes to fix conflicts and to add vectorization support after #6794 or really had the chance to make any material progress on finishing it.

I think the next steps are creating a version of FastPFOR in pure Java that is compatible with the C++ version, that preferably reads to/writes from little endian `ByteBuffer` from the mapped segments so that the simpler interfaces defined in the 'native' version of the branch can be used. Besides making it so we can utilize the faster JNI/native version when available (which is how lz4-java currently behaves), and it also doesn't suffer from the additional heap memory footprint that the version in the PR has.

In https://github.com/lemire/FastPFor/issues/42, @lemire has suggested that making a compatible version is non-trivial but might not take more than a few days or a week or so. My problem has been finding a continuous chunk of time to devote to fully understanding the C++ implementation and then of course doing the compatible Java implementation.

Much of the benchmarking will need repeated against the latest version of Druid, with a more heavy focus on vectorized reads, though I was already benchmarking against #6794 while it was in progress and my branch was competitive at the time, so many of the measurements might still be close to true.

The other part that has given me some pause more recently, is thinking about how potentially more of the low level column reads of Druid could be pushed into native code, beyond just decompressing chunks of values, and what that might look like and how that might change implementation of what has been done in the prototype thus far (if at all). I expect the strategy and physical column layout itself wouldn't really change, just a lot more of the code implemented in java right now would be pushed to native code, so this might not be worth worrying too much about.

Lastly, for some further thinking with regards to native processing, I think there are probably some unresolved questions about whether the new column format suggested in my PR (or any larger segment format) changes would be worth further modifying so that data in the segment would be well aligned to work with vectorized CPU instructions. This might not be an issue worth considering at all, I mostly want to make sure because segment format changes are among the riskiest changes to make. Once released they must remain supported for backwards compatibility for very long cycles, so it feels very important to get any new stuff right.

Anyway, thanks for bringing this issue back to my attention and starting the discussion. Thinking about it to respond to your question has given me some motivation to .. well at minimum at least keep thinking about it a bit more, but maybe we can actually get this moving again :sweat_smile:.

**Comment by CmdrKeen** [comment]
For what it's worth, I appreciated the wall of text @clintropolis :) It helps provide insight! 

No pressure, just always excited by efficiency gains! 👍
