### ISSUE TITLE
Inconsistencies around Float and Long columns

### ISSUE THREAD

**Issue by leventov** [apache/druid#4503]
1. In `FloatDimensionIndexer.processRowValsToUnsortedEncodedKeyComponent()`, (similar for Long), `DimensionHandlerUtils.convertObjectToFloat()` may return null (on parse error), but other code doesn't expect nulls: e. g. `getUnsortedEncodedKeyComponentHashCode()`, `checkUnsortedEncodedKeyComponentsEqual()`, `compareUnsortedEncodedKeyComponents()` don't expect null inputs
 2. Also `FloatDimensionIndexer.processRowValsToUnsortedEncodedKeyComponent()` doesn't accept List of a single element, however it probably should.
 3. `DimensionHandlerUtils.convertObjectToFloat()` converts `null` to 0 itself, however it doesn't make this method entirely non-null (as said above, on parse errors nulls are still returned). It may matter in `FloatValueMatcherColumnSelectorStrategy`.

@jon-wei @gianm thoughts?

**Comment by gianm** [comment]
Will this lead to exceptions or crashes? Or 'weird' results? It's not obvious to me, at first glance, what is the best way to resolve the inconsistencies. The first two things that come to mind are,

- always treat null as 0
- treat null as "not a number" in cases where that makes sense -- so treat it as a parse exception when indexing, and don't allow it to match _any_ number in a value matcher, etc.

**Comment by leventov** [comment]
Yes, item 1. in my list may lead to crashes, however float/long ingestion is not supported currently at all, because `toTimeAndDims()` uses `Row.getDimension()` that returns `List<String>` and will be unconditionally rejected by Long and Float indexers now. It should probably use `Row.getRaw()`?

I think it's reasonable to always treat null as 0, and parse errors as `NaN` (however currently parse errors are also mapped to 0). But `NaN` does match other `NaN` (at least it should be -- using conversion `floatToIntBits()`), it was my idea when float columns were introduced and I think it's reasonable.

**Comment by jon-wei** [comment]
For point 1:
Regarding crash/exception potential, `getUnsortedEncodedKeyComponentHashCode()` and `checkUnsortedEncodedKeyComponentsEqual()` will cause a NullPointerException on unparseable values, but `compareUnsortedEncodedKeyComponents()` won't since its call site checks for nulls before calling.

regarding this point:
> however float/long ingestion is not supported currently at all, because toTimeAndDims() uses Row.getDimension() that returns `List<String>` and will be unconditionally rejected by Long and Float indexers now. It should probably use Row.getRaw()?

As-is float/long ingestion will get an exception with unparseable values but otherwise it would work, `toTimeAndDims()` calls `row.getDimensions()` to get a `List<String>` of dimension names, but uses `Row.getRaw()` to read the row values:

```
        Object dimsKey = indexer.processRowValsToUnsortedEncodedKeyComponent(row.getRaw(dimension));
```

For point 2:
I think that's reasonable, it can just pull the value out of the list and treat it as a single value

For point 3 and general thoughts on ingesting nulls/unparseable values:
Maybe we should treat all null and unparseable ingested values as 0 for numeric columns. 

If we use "null" to indicate "invalid number", how would we represent this when persisting the index to disk? I don't think the existing segment format has a way to store nulls for numeric columns.

If we use NaN to indicate "invalid number" for Floats, it seems like we would have no equivalent for Longs. Are we okay with that inconsistency?
