### ISSUE TITLE
Configurable HyperLogLog accuracy

### ISSUE THREAD

**Issue by DaimonPl** [apache/druid#4617]
Even though current algorithm claims to be "98% right" we've found that error is sometimes even around 4-5%

Idea is to have ability to increase accuracy (at the cost of speed and space) for such cases.

I assume that for proper estimation entire datasource would need to be aggregated with same accuracy setting

Is number of buckets proper candidate for accuracy prameter?

**Comment by DaimonPl** [comment]
@gianm maybe you have some ideas about this one? :)

**Comment by DaimonPl** [comment]
@leventov @fjy maybe you? :)

**Comment by gianm** [comment]
@DaimonPl some thoughts:

- The "98% right" thing is meant to refer to average error of HyperLogLog, but certainly the error in any particular case can be greater than that.
- Druid's implementation deviates from the standard algorithm (see http://druid.io/blog/2014/02/18/hyperloglog-optimizations-for-real-world-systems.html) in a way that decreases storage space but can increase the error slightly in some cases.
- Yes changing the number of buckets is a good way to improve the accuracy. In addition you could undo the storage space optimization.
- But watch out since both of the above changes would affect the storage format, meaning you may be incompatible with already-written hyperUnique columns.

**Comment by elverkilde** [comment]
We are also observing large errors (7-8%) especially on smaller cardinalities (<40000). This is pretty much in line with the bias observed in the Google paper.

Did you consider any of the improvements mentioned in the Google paper (HyperLogLog++)?

**Comment by leventov** [comment]
Related: #7160
