### ISSUE TITLE
Another approach to capping work set size during groupBy

### ISSUE THREAD

**Issue by leventov** [apache/druid#4771]
Rather than attempting to estimate heap footprint (see #4768), we could just make all involved data structures (lists, arrays, maps) not resizeable beyond the configured limit. The only thing that is not controllable so easily is the string data: we may group by really short or really long strings. So instead of storing them as `String` objects, we could also store them in a ByteBuffer of limited size, and operate with offsets within that ByteBuffer, where currently `String` pointers are used. It should be also more efficient, because of less indirection and less footprint (we don't need to have `String` objects and `char[]` headers in heap).

**Comment by gianm** [comment]
The reason I originally had groupBy use String objects rather than byte buffers is that Strings are what you get from DimensionSelectors, and it's what the queries need to return when they generate their results. It's expensive to switch to a byte array form just for the dictionary, since it involves a lot of extra copying, possibly even encoding/decoding (if the buffers are utf8 bytes rather than char arrays), and ultimately creates extra String garbage since the buffers would need to become Strings again at some point.

I think we could imagine a world where DimensionSelector.lookupName returns a utf8-encoded ByteBuffer (or Memory or whatever) rather than a String, and the query system keeps it in that form as long as it can. Then the dictionary could be a buffer like you described without so much overhead.

Maybe for simple queries, we could get away with never converting to String, if we also add a Jackson serializer for whatever kind of buffer object we use instead.

**Comment by jihoonson** [comment]
I think this idea is better than #4768 if it's done with a proper change for DimentionSelector.lookupName() to return a string stored in off-heap.
