### ISSUE TITLE
Exceptions in broker: Channel disconnected

### ISSUE THREAD

**Issue by fanwu72** [apache/druid#5340]
Hi there,

Some queries(dozens every day) fails in my production environment. I found below exceptions from the broker logs. It seems that the connection between broker and peon gets disconnected during querying. 

`2018-02-03 09:41:01,115 ERROR io.druid.server.QueryResource: Exception handling request: {class=io.druid.server.QueryResource, exceptionType=class io.druid.java.util.common.RE, exceptionMessage=Failure getting results for query[7ea45567-4826-4987-adf6-5f77ee1e9e47] url[http://xf5x243:8100/druid/v2/] because of [org.jboss.netty.channel.ChannelException: Channel disconnected], exception=io.druid.java.util.common.RE: Failure getting results for query[7ea45567-4826-4987-adf6-5f77ee1e9e47] url[http://xf5x243:8100/druid/v2/] because of [org.jboss.netty.channel.ChannelException: Channel disconnected], query=GroupByQuery ... ...`

Without any retry mechanism, the query just fails. My proposal is to retry in my client application. Besides, could anyone help me to understand what happens in the server side and any configuration changes I can do? 
 
The druid version is 0.10.1 and tranquility kafka is adopted for real-time ingestion.

Best regards,
Ryan

**Comment by drcrallen** [comment]
If I recall this was fixed recently to allow peons to soft-shutdown and not just kill queries.

**Comment by fanwu72** [comment]
@drcrallen Thanks for the reply.  If the root cause is the peon shutdown, the issue should occurs periodically, but it is not. Could you please tell me the relevant issue or commit? I'll check it. Thanks again.

Best regards,
Ryan

**Comment by gianm** [comment]
@fanwu72 I think the PR that @drcrallen was talking about is https://github.com/druid-io/druid/pull/4716. It looks like it hasn't been merged yet.

Another thing that could cause disconnects is https://github.com/druid-io/druid/issues/3393 which will have a fix in 0.12.0 (https://github.com/metamx/java-util/pull/73 was incorporated by way of #5289).

**Comment by fanwu72** [comment]
Thank you @gianm

**Comment by pdeva** [comment]
it seems this issue is still present in 0.12.1 #6117

**Comment by prabakarankrishnan** [comment]
Hi All
I am having 0.10.1 version in Druid. I am having a issue while trigring multiday concurrent query . I am facing below exception:
ERROR QueryResource:130 - Exception handling request: {class=io.druid.server.QueryResource, exceptionType=class io.druid.java.util.common.RE, exceptionMessage=Failure getting results for query[key] url[http://ip:port/druid/v2/] because of [org.jboss.netty.channel.ChannelException: Channel disconnected].

Is this issue fixed in 0.13 or we have any fix with 0.10.1 version itself?

**Comment by eagoo** [comment]
en,0.12.1 still has this exception Failure getting results from[http://host:port/druid/v2/] because of [org.jboss.netty.channel.ChannelException: Channel disconnected

**Comment by UmerHamid** [comment]
I'm new in druid community and want to deep learn about druid.
When query on a large data (16gb) my historal node has fail and occur this type of error in dsql.

rg.apache.druid.java.util.common.RE: Failure getting results for query[77d971a0-2b10-4a19-a086-f6fe393478a8] url[http://localhost:8083/druid/v2/] because of [org.jboss.netty.channel.ChannelException: Channel disconnected].

How it can be resolved?

**Comment by tvorogme** [comment]
Same issue, don't know how to resolve? I need to add more http workers or what?

**Comment by wc188996** [comment]
I have the same issue when using imply--2.8.20, My solution is increase the druid.processing.numThreads ,the path is imply-2.8.20/conf/druid/historical/runtime.properties.
the occurrence of this error is t0o many queries in one time, and not enough threads to work at this time.

**Comment by lejinghu** [comment]
Seeing this issue when doing large group by queries..

**Comment by Green-Angry-Bird** [comment]
For anyone else that comes across this. Indeed, increasing `druid.processing.numThreads` on both my broker and historical solved this problem. A corresponding increase to `-XX:MaxDirectMemorySize` is also needed.

Note, when I simultaneously increased `druid.processing.numMergeBuffers` to the recommended 1/4 value of `numThreads` I still had the issue. So to solve the issue I had to increase `druid.processing.numThreads` but keep `druid.processing.numMergeBuffers` untouched.

**Comment by tbotalla** [comment]
In my case increasing the JVM heap size on historical/jvm.config with -Xmx2048m solved the issue.
