### ISSUE TITLE
Structured approach to segment format evolving and versioning

### ISSUE THREAD

**Issue by leventov** [apache/druid#5347]
In order to enable innovation in segment format (see [`Segment Format and Ser/De`](https://github.com/druid-io/druid/labels/Area%20-%20Segment%20Format%20and%20Ser%2FDe) tag) I think some system should be developed, so that when somebody want to improve something in the segment format, very little work is required, except actual segment format (and consequently query engines) changes. Currently there is a prohibitive barrier, the mark of this is that almost no improvements were done in segment format in the last few years.

I'm not sure even about the list of requirements, but something that might be included:
 - Ability to make even small improvements in segment format, not needing a change to be big to justify it
 - Minimum or no "custom flags" needed to enable/disable features, e. g. see #5278, "buildV9Directly" (still present in Druid source code!), etc.
 - Ability to rollback to previous druid version

Something that could be done, again, very unsure about specifics:
 - Druid version is synchronized with segment version?
 - Global indexing of serializers, to be independent of class names
 - New segment format features become "incubating" and they are enabled by one flag/property (just one for all features), and automatically "promoted" in the next druid version. It should be automatic, without requiring extra PRs.

Please suggest both requirements and ideas.

@nishantmonu51 @gianm @drcrallen @himanshug

**Comment by gianm** [comment]
Well, I think it would be great if it was easier to add features to the storage format, so it's a good area of discussion.

A question: what do you mean by "segment format"? Like the structure of the segment itself (meta.smoosh, columns with `ColumnPartSerde` headers, etc)? Or the structure of individual columns?

I would add one other requirement: long term backwards-compatibility towards written segments. It is really useful for new Druid versions to be able to read very old Druid segments (since it adds complexity and cost to ask users to periodically reindex all of their old data with a new segment format).

> Currently there is a prohibitive barrier, the mark of this is that almost no improvements were done in segment format in the last few years.

What do you think the most prohibitive barrier is?

> New segment format features become "incubating" and they are enabled by one flag/property (just one for all features), and automatically "promoted" in the next druid version. It should be automatic, without requiring extra PRs.

I am skeptical that a one-size-fits-all flag will work, since if we imagine a world where we are really doing a lot of experiments on column format, then inevitably some experiments will be more stable than others. So I am in favor of a way for users to opt in to certain features "early" and then later on, those features could become automatic. To me it makes sense for users to opt in to flags in their `IndexSpec` at indexing time (by specifying them by string name in a list, so we don't need special serde code for each flag). And then for those flags to be passed to the indexing code in one single object, like `Set<IndexFlag>`. I imagine this would only be on the _writing_ side; on the reading side the server should support any flag that its version of the code knows about. You should not have to "enable" anything to get a historical node to load a segment written with some new flag.

**Comment by leventov** [comment]
> A question: what do you mean by "segment format"? Like the structure of the segment itself (meta.smoosh, columns with ColumnPartSerde headers, etc)? Or the structure of individual columns?

I don't have a clear picture. If we are talking about about what should be changed as the result of this discussion, it might be:
 - On-disk data formats, but probably only around writing versions and/or "serializer codes" somewhere in headers/metadata. Improvements to formats themselves (like new dictionary format) is not subject of this discussion, but it should be enabled (or eased) by the changes about which we are talking about here.
 - Reorganization of source code. Logic, refactoring, naming, packages, etc.
 - Properties/configurations, like "enable incubating segment format features" suggested above. Btw "incubating" is not a good term for it, but whatever.
 - Documentation updates. Both user documentation and developer docs (how to add new feature).

> I would add one other requirement: long term backwards-compatibility towards written segments. It is really useful for new Druid versions to be able to read very old Druid segments (since it adds complexity and cost to ask users to periodically reindex all of their old data with a new segment format).

Also to enable many iterations of the same format and not making code tree a complete mess, some structuring and strict naming conventions might need to be applied. E. g. a separate package for each logical thing (like int column, double column, etc.)

> What do you think the most prohibitive barrier is?

To begin with, there is no docs or precise instruction, what I should do, if I want to add a new incompatible version of some part of segment format, e. g. indexed column. Everybody is supposed to figure it out himself (that's very hard, btw.) Adding custom "enabling options" for features, also. That are just first two things that came into my mind.

> I am skeptical that a one-size-fits-all flag will work, since if we imagine a world where we are really doing a lot of experiments on column format, then inevitably some experiments will be more stable than others.

If a feature could be beneficial in some cases and not in other, of cause there should be a specific flag. But there are a lot (I think overhelming majority) of segment features that are undoubtful improvements. But we still need to put them under a flag (temprorarily) to enable rollbacks. This flag could "always exist" and be standartized.

**Comment by gianm** [comment]
@clintropolis has been looking at adding new integer encodings for the data section of string columns and has run into confusion as well about the best way to extend the current system.

@clintropolis - maybe you can suggest some ways to improve it based on your experience doing this investigation?
