### ISSUE TITLE
Fix Incoherency in Expression Selectors 

### ISSUE THREAD

**Issue by nishantmonu51** [apache/druid#5406]
Review comment - https://github.com/druid-io/druid/pull/5278#discussion_r169359642
There is an incoherency. This is a selector of ExprEval, not of ExprEval.value(). This class is used only in ExpressionSelectors.makeExprEvalSelector(). This incoherency already causes problems in AggregatorUtil: ExpressionSelectors.makeExprEvalSelector() is used there only to call getObject(), not taking advantage of ConstantColumnValueSelector optimization.

To make things more coherent, either

ExpressionSelectors.makeExprEvalSelector() should return ColumnValueSelector<T>, not of ExprEval (with according changes)
Or Supplier<ExprEval> should be returned from this method, enforcing all clients to go via get().asDouble() path (and ConstantColumnValueSelector should adapt accordingly).

**Comment by nishantmonu51** [comment]
+cc @gianm for thoughts.

**Comment by gianm** [comment]
The main reason I did this was because some selectors wrap expression selectors and prefer an `ExprEval` object so they can get object casting behavior (`asDouble`, `asString`, etc). If we have some standard functions for casting `Object` to various Druid types then I think the ExprEval selectors aren't needed, and we can go with the first solution: "ExpressionSelectors.makeExprEvalSelector() should return ColumnValueSelector, not of ExprEval"

**Comment by gianm** [comment]
Btw, there is no incoherency that I'm aware of in the current code. It is just confusing since there are both ExprEval selectors and normal value Object selectors, and callers have to use the right one.

**Comment by nishantmonu51** [comment]
Thanks for your thoughts @gianm. Will refactor things accordingly in a follow up PR. 
the incoherancy in comment here is for the newly added isNull method, which returns false for ObjectSelectors instead of computing the object and determine its nullability for performance reasons.

**Comment by leventov** [comment]
@gianm the fact that `AggregatorUtil` misses the optimization at the moment is the sign of the inconsistency.
