### ISSUE TITLE
RemoteTaskRunnerConfig/HttpRemoteTaskRunnerConfig equals() and hashCode() inconsistency

### ISSUE THREAD

**Issue by leventov** [apache/druid#5458]
`HttpRemoteTaskRunnerConfig` extends `RemoteTaskRunnerConfig` and adds more fields, but doesn't override `equals()` and `hashCode()`. While `RemoteTaskRunnerConfig` uses `getClass()` comparison in `equals()`, that breaks the substitution principle.

**Comment by gianm** [comment]
I don't think it is universally accepted that strictly adhering to the substitution principle in Java is a good thing. Using getClass has a benefit: `x.equals(y)` may return true improperly if y's class extends x's class and adds more fields. They are really not equal in that case (y, with more fields added, is really a different kind of thing from x). For this reason I usually use getClass rather than instanceof when writing equals methods.

**Comment by gianm** [comment]
I acknowledge that this is controversial, though: https://www.artima.com/intv/bloch17.html

**Comment by leventov** [comment]
The approach when there is no such controversal class extensions, and composition is used instead, leaves no surprises. As far as I understand, we use extension because we don't want to add another level of nesting in configs. I wonder if there is an option to "flatten" such nested entities in Jackson.

**Comment by gianm** [comment]
> The approach when there is no such controversal class extensions, and composition is used instead, leaves no surprises. As far as I understand, we use extension because we don't want to add another level of nesting in configs. I wonder if there is an option to "flatten" such nested entities in Jackson.

I think that's indeed the reason that HttpRemoteTaskRunnerConfig extends RemoteTaskRunnerConfig.

We could simply copy and paste rather than doing a subclass, but I think we want to reduce code duplication and the maintenance burden it adds. One compromise could be to do composition, but flatten manually in the new class's constructor. It creates some more code in the new class (a constructor is needed) but avoids both the problems of equals and of too much code duplication. I don't know if Jackson has an option to do it automatically or not.
