### ISSUE TITLE
gcloud pubsub support

### ISSUE THREAD

**Issue by tekjar** [apache/druid#5773]
Hi. I want to read data from gcloud pubsub and load it into druid.

http://druid.io/docs/0.12.0/ingestion/stream-ingestion.html

Docs suggest that there are 2 ways. What is the recommended way?

**Comment by b-slim** [comment]
Hi, if my understanding of google pubsub is correct, you need to use a Pull based method. In other words this is not up to Druid, Druid allows both since the choice is depending on the what the queue/streaming system supports.

**Comment by glasser** [comment]
As of 0.14, the Kafka service is abstracted out enough that it also supports AWS Kinesis, so it seems feasible to make it support this too.

**Comment by aditya-r-m** [comment]
@glasser the shared service for Kafka & Kinesis can't support pubsub.
Primary reasons being the following,

1. Instead of offsets & commits, pubsub subscribers work with pulling packets in batch from cloud & sending acks.
2. There is no concept of partitions or strictly ordered logs in pubsub, topics are fully replicated into multiple subscriptions which do not provide strong ordering guarantees when pulling packets.

I have created a very primitive working implementation for pubsub supervisors/tasks & the extension doesn't share much with the kafka/kinesis specific handling apart from package & config structure.

**Comment by marklu2018** [comment]
@aditya-r-m , why would the Pubsub indexing service care about the ordering of packets? Could it just index those pulled packets as it arrives?

**Comment by aditya-r-m** [comment]
@marklu2018 agreed, you are right in that ordering won't be needed to ingest data into druid from pubsub.

To brief you on the context, in the druid code base, SeekableStream supervisor service relies on ordering of packets & sequence numbers for checkpointing. & task replicas are created to ensure that all the partitions are reliably being read from.

Pubsub being a global queue without any hardwired partitioning, we will not need task replicas & thus, sequence number based check-pointing shouldn't be required. Sensible acks should do the job.

This has implications on how pubsub indexing implementation will differ from Kafka & Kinesis. So we can't derive another child class from SeekableStream package & use it for Pubsub as was suggested by @glasser.
