### ISSUE TITLE
opentsdb-emitter fails to push metrics

### ISSUE THREAD

**Issue by hefei1986** [apache/druid#5820]
Opentsdb logs as follows: 
20:23:04.230 WARN  [PutDataPointRpc.execute] - Invalid tag value ("bd-prod-rt-olap0:8082"): illegal character: :: metric=query.cpu.time ts=1527769336 value=1101 service=druid/broker host=bd-prod-rt-olap0:8082 type=segmentMetadata dataSource=accesslog-tranquility-seller-log

tag value should be sanitized too.
![image](https://user-images.githubusercontent.com/1287334/40782699-c206f85a-6512-11e8-9558-860421f574be.png)

**Comment by hefei1986** [comment]
20:44:23.821 WARN  [PutDataPointRpc.execute] - Invalid tag value ("bd-prod-rt-olap0:8082"): illegal character: :: metric=jvm.bufferpool.used ts=1527770663 value=542157766 service=druid.broker host=bd-prod-rt-olap0:8082

**Comment by bjozet** [comment]
This was fixed in commit 85391e9fb3cef355dacbbf5c443773fb7aab445a, and subsequently modified in 8f3fe9cd028592b4b1449c2a5e6dba482bed0549

Currently the tags are sanitized in EventConverter.java lines [75-76](https://github.com/apache/druid/blob/master/extensions-contrib/opentsdb-emitter/src/main/java/org/apache/druid/emitter/opentsdb/EventConverter.java#L75-L76)

@gianm : I suspect this can be closed.
