### ISSUE TITLE
Query result merges improperly occur in jetty threads

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#5885]
When queries have very large quantity of results, the merges happen on the jetty threads and can cause significant cpu load under high concurrent query load. As an example, a "large threshold" topN against a hyper-unique aggregator can cause a cpu-time flame graph on brokers similar to this:

<img width="1423" alt="screen shot 2018-06-15 at 9 29 58 am" src="https://user-images.githubusercontent.com/8213081/41479254-6f9966fc-707f-11e8-818b-b58fc5f804d0.png">

You'll notice the merge sequence yielder applies the topn merge functions in the stack trace of the query resource `doPost` method. This work and its prioritization is completely untracked by the processing queues which include the concept of query priority. That means under heavy contention, it is impossible to predict how the jetty threads will get priority, and impossible to tell exactly what their contention with the processing threads will be.

This is expected to affect historicals when there are many large segment results to merge (like big group by or topn results) as well as brokers in larger clusters (couple hundred nodes or more).

A couple solutions that could work include:

1. using the processing executor service with properly set query priority runnables. This has a risk of deadlock if not handled correctly, where all threads are taken up by merge needs without the ability for worker sub-tasks to do their thing.
1. using a fork-join pool, but with proper query priority understanding.

Putting such things in place can help with large result set merges and speed up query time as well as increase predictability of performance by honoring query priority settings.

**Comment by drcrallen** [comment]
Flame graph was done with https://cloud.google.com/profiler/docs/profiling-java using default timing settings.

**Comment by gianm** [comment]
Out of curiosity do you have the cache enabled on the broker? It would make it need to do merges of results for every segment which doesn't scale super well. I would think this merging resources situation could be annoying even without that, but that would definitely make it worse.

Fwiw, I wouldn't call it "improper" since this is how it is designed (merges happen in http threads even on historicals -- the processing threads are really only used for per-segment stuff). But it does sound like we can do better.

> 1) using the processing executor service with properly set query priority runnables. This has a risk of deadlock if not handled correctly, where all threads are taken up by merge needs without the ability for worker sub-tasks to do their thing.

This seems like the best way to approach it, but we have to be careful to chunk up the work into small enough chunks so a big merge doesn't starve out the processing pool.

Also the flame graph is pretty rad 😎

**Comment by drcrallen** [comment]
Caching is not enabled on brokers in this case
