### ISSUE TITLE
Metrics might not capture time or work done on historicals.

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#5886]
The work done on historicals may not be properly accounted in the metrics emitting query runner.

<img width="1429" alt="screen shot 2018-06-15 at 10 37 07 am" src="https://user-images.githubusercontent.com/8213081/41481816-384cf8ae-7088-11e8-9801-f215707f99e9.png">

The above is a cpu-time flame graph of the call stack of work on historicals. You can see that the metrics emitting query runner call stack only captures a small portion of the overall work! The CPU time accumulator (further up the call stack) seems to capture the whole stack.

This can be corroborated by taking a specific query id and comparing the `query/time` reported by the historicals for a particular `host` and the `query/node/time` reported by the brokers for the historical as the `server`. They do not match up at all on one of the systems I'm looking at. Numbers reported as `query/time` are very small compared to `query/node/time` for specific query ids.

I would appreciate if someone could check on their cluster as well to see if this matches up with their experience.

Looking at `io.druid.server.coordination.ServerManager#buildAndDecorateQueryRunner` and this call stack, it looks like the "work" for aggregation is actually being done somewhere in `SpecificSegmentQueryRunner` in an unexpected way. This is a really tricky interplay of code, and any changes to "fix" a problem would need to be carefully vetted that they actually capture the metrics intended.

It is also concerning that the reference counting segment runner doesn't have a direct lineage trace to the things that are doing lz4 decompression of aggregations.

**Comment by gianm** [comment]
The flame chart may be misleading here. The way the query runner stack is supposed to work is that `QueryRunner.run` prepares a Sequence, which is then accumulated in a later step. The code that drives this is in ChainedExecutionQueryRunner.

```java
                                    Sequence<T> result = input.run(threadSafeQueryPlus, responseContext);
                                    if (result == null) {
                                      throw new ISE("Got a null result! Segments are missing!");
                                    }

                                    List<T> retVal = result.toList();
```

The call stack for the `result.toList()` part might not mention all of the QueryRunners, since not every QueryRunner leaves a piece of itself behind in the Sequence. For example the reference counting runner does:

```java
        final Sequence<T> baseSequence = factory.createRunner(adapter).run(queryPlus, responseContext);

        return Sequences.withBaggage(baseSequence, adapter.decrementOnceCloseable());
```

And so it won't appear in the call stack for accumulate.

**Comment by leventov** [comment]
I agree with Gian. `MetricsEmittingQueryRunner` works by means of wrapping a Sequence. You could notice several `WrappingSequence` stacks in the larger part of the flamegraph. I think one of them corresponds to `MetricsEmittingQueryRunner`.

I always found CPU time metrics to be pretty accurate. For example, when `PooledTopN*` classes were introduced that you could see in the stack, specifically CPU time metrics indicated the efficiency improvement: https://github.com/druid-io/druid/issues/3798#issue-197280025

**Comment by drcrallen** [comment]
It is not the cpu time I'm saying doesn't match it, it is the node time from the view of the broker vs the query time from the point of view of the historicals.

**Comment by gianm** [comment]
> It is not the cpu time I'm saying doesn't match it, it is the node time from the view of the broker vs the query time from the point of view of the historicals.

Is it possible this is due to another one of these possible reasons?

- The `druid.server.http.numThreads` limit has been reached on the historicals. In this case, `query/time` would be smaller than `query/node/time`, since `query/time` measures from when an http thread picks up the query. But a query could spend substantial time waiting for an http thread to pick it up.
- The `druid.broker.http.numConnections` limit has been reached on the broker. Same deal, but the concurrency limit is client-side rather than server-side.
