### ISSUE TITLE
Missing doc for RegisteredLookup DimensionSpecs?

### ISSUE THREAD

**Issue by QubitPi** [apache/druid#5895]
I found doc for Lookup DimensionSpecs in drui.io/docs/latest/querying/dimensionspecs.html, but not for RegisteredLookup

**Comment by josephglanville** [comment]
It's documented but poorly.
Basically instead of using `lookup` with the lookup extraction definition you specify `name` as the name of a registered lookup.
The 2 options are mutually exclusive, if `name` is specified then the LookupReferencesManager will be called to build the extraction function, otherwise `lookup` is used.
The language on that page isn't great, if I have some time I might try make it clearer.
It should also be more clear how to use them on this page too: http://druid.io/docs/latest/querying/lookups.html

**Comment by gianm** [comment]
Good point. @QubitPi, @josephglanville, are either of you interested in updating the docs to be clearer?

**Comment by QubitPi** [comment]
@josephglanville , @gianm Thank you for the update. My team uses registered lookup and I have experience developing extensions on top of it. I can find some time as soon as possible to update the doc.
