### ISSUE TITLE
Merge vs. Compact - What's the difference?

### ISSUE THREAD

**Issue by teeram** [apache/druid#5936]
Hello, I have a question pertaining to what the difference is between running a Merge Task and a Compact Task.  Particularly, what is the difference between a Same Interval Merge Task and a Compact Task?  It seems that a Compact Task starts a new indexing job under the hood that uses a Firehose to a) read all the existing segment data and b) create a brand new re-indexed segment(s) from the existing data.  I'm a little blurry on how the Same Interval Merge Task differs, but it seems to focus on combining the data instead of a total re-index.  Could someone help clarify the differences between these two tasks?  Also it would be nice to know the general rule for when I should use a Same Interval Merge Task instead of a Compact Task and vice versa.

Thank you!

**Comment by gianm** [comment]
The compact task is meant to be a nicer interface to the "index" task. It basically creates an index task with the proper config to repartition a chunk of segments (by reading them in and then re-writing them). It may repartition N input segments to M output segments.

The merge task makes _one_ output segment and is coded specifically to read segments itself, rather than to generate an index task that does the same. I'm not sure if its performance is any different from the compact task. Its restriction that it must generate one single output segment means that it's somewhat less flexible.

Fwiw the compact task is part of us trying to achieve a vision of flexible, scalable automatic compaction in Druid. So hopefully that becomes the way of the future.

**Comment by teeram** [comment]
Gotcha, thanks @gianm, very much appreciate the info.
