### ISSUE TITLE
allow 'secondary' deep storage to easily allow deep storage migration

### ISSUE THREAD

**Issue by pdeva** [apache/druid#6046]
currently if you want to migrate your deep storage, it is a very manual procedure, with tons of downtime.

To automate this, Druid needs the ability to specify a 'secondary' deep storage.
This way, if i want to migrate from say S3 to GCloud, I would:

1. Specify both S3 and GCloud as deep storage.
2. All segments from here on are stored in *both* deep storages
3. When fetching, both deep storages are checked for presence of segment
4. When time interval 'x' has passed, enough segments would have been stored in Gcloud that i would turn off 'S3' deep storage. 

The above would result in deep storage migration gradually and without any downtime.

**Comment by gianm** [comment]
How does the following procedure look for an S3 -> GC migration? It is similar to how I have done Druid deep storage migrations in the past.

1. Specify GC as deep storage. Now new segments from here on are stored in GC. Old segments continue to be fetched from S3 when necessary.
2. Copy all older segments from S3 to GC.
3. Update metadata store payloads for the old segments to use GC loadSpecs instead of S3 loadSpecs.
4. Restart the coordinator to make sure it doesn't still have any of the old loadSpecs cached. (I am not sure if this is necessary, but why not.)
5. At this point it is safe to delete the old segments from S3, if you want.

**Comment by pdeva** [comment]
i am a little confused.

>Old segments continue to be fetched from S3 when necessary.
How will druid know about S3 in the first place, now that you have specified GC as the deep storage?


>Update metadata store payloads for the old segments to use GC loadSpecs
I assume 'metadata store payloads' refers to data in the metadata storage.
Assuming that, it seems this requires manually modifying the data in metadata storage. 
Not only is this undocumented, this could lead to corruption of the metadata if done incorrectly.
There should be some tooling for this.

**Comment by pdeva** [comment]
>How will druid know about S3 in the first place, now that you have specified GC as the deep storage?
ahh i guess that is because the metadata refers to those segments in S3. right?
