### ISSUE TITLE
Possible performance issue during DruidSchema metadata refresh

### ISSUE THREAD

**Issue by egor-ryashin** [apache/druid#6097]
`Druid Broker 0.11.0` with `druid.sql.enable=true` produces much more garbage than usual, profiling shows a lot of `Object[]` which are referenced by `TreeMap$Entry` which eventually leads to `io.druid.sql.calcite.schema.DruidSchema#refreshSegments`. I speculate it constantly refreshes metadata for every segment. With `-Xmx5G` and 1mln segments it leads to unresponsive service due to GC. Meanwhile it works fine with `druid.sql.enable=false`.

**Comment by gianm** [comment]
Hi @egor-ryashin,

There have been some improvements to the refreshing mechanism in later versions (try 0.12.1?). It doesn't constantly refresh metadata for historical segments, but it does refresh periodically for realtime segments, which is important because new columns can show up at any time. However, the metadata does take up space, so if you were running kind of close to heap max with `druid.sql.enable=false` before then you'll need more heap in order to enable SQL.
