### ISSUE TITLE
Kafka indexing from multiple topics into single datasource

### ISSUE THREAD

**Issue by mohangaradi** [apache/druid#6275]
Hi,

Is it possible to ingest data from multiple topics into a single data source in kafka indexing ? or does it still have to go through tranquility kafka indexing with matching topics ?

Thanks.

**Comment by dclim** [comment]
This is not currently supported, but is a relatively common request. The recommended approach is to use something like Kafka Streams to aggregate the data from multiple topics into a single topic and then ingest that using the Kafka indexing service. Tranquility Kafka is deprecated and is no longer recommended for Kafka ingestion because of its best-effort behavior and other limitations.
