### ISSUE TITLE
include router node in rolling upgrade documentation

### ISSUE THREAD

**Issue by pdeva** [apache/druid#6284]
that node is missing in the order of list of nodes to upgrade

**Comment by himanshug** [comment]
speaking from personal experience, typically you would upgrade it in the very end.

however, router had many bugs which got fixed over time and it appears to work but still considered experimental. at one point there were thoughts of removing it altogether.
router not being mentioned much is due to its unofficial position in the code with no standing whether to really support it in the long term.
given that multiple people use it, so it must be useful and should probably be made a first class citizen.

**Comment by glasser** [comment]
Given that the router is where the new web console lives, it is presumably no longer considered so experimental and should probably get added to `docs/operations/rolling-updates.md`?

**Comment by himanshug** [comment]
I agree.

**Comment by glasser** [comment]
Confirmed it is still not listed.
