### ISSUE TITLE
IncrementalIndex generally overestimates theta sketch size

### ISSUE THREAD

**Issue by gianm** [apache/druid#6743]
Theta sketches have a very large max size by default, relative to typical row sizes (about 250KB with "size" set to the default of 16384). The ingestion-time row size estimator (getMaxBytesPerRowForAggregators in OnheapIncrementalIndex) uses this figure to estimate row sizes when theta sketches are used at ingestion time, leading to way more spills than is reasonable. It would be better to use an estimate based more on actual current size. I'm not sure how to get this, though.

@leerho - or anyone else - do you have any ideas or suggestions?

**Comment by AlexanderSaydakov** [comment]
I don't see any way around this given the existing protocol. Druid asks the maximum size. And there is no distinction between the size in memory (slot in BufferAggregator) and serialized size in the segment. The 250KB is the absolute maximum size in memory, so that sketches always fit into those BufferAggregator slots. The method to get this size is getMaxIntermediateSize() in AggregatorFactory (note "intermediate" in the name).
A serialized result should be about 130KB max. If the intention is to have the serialized size in IncrementalIndex, then, perhaps, another method in AggregatorFactory can be introduced (say, getMaxSerializedSize() or something like that)

**Comment by gianm** [comment]
@AlexanderSaydakov One weird thing about how the ingestion-time row size estimator works is that it's using on-heap Aggregators, but it estimates size via the AggregatorFactory `getMaxIntermediateSize()` method that is meant to be the max size of a buffer needed for the BufferAggregator.

One thing we could do is add a method to Aggregator (the on-heap interface) that estimates the current on-heap footprint. It can vary in a way that BufferAggregator, currently, can't.

Another thing we could do is implement growable BufferAggregators and switch IncrementalIndex to use those instead. It has come up before, see proposal from @himanshug in https://github.com/apache/incubator-druid/issues/2963, but isn't implemented.

**Comment by leerho** [comment]
@gianm 

I don't have a deep understanding of the inner workings of the memory allocation strategy in Druid, but I should point out that the current model of allocating equal sized slots in a Buffer where each slot is the maximum possible size of a sketch Is very likely a horrible waste of memory space.  

Sketches, are designed to start very small in their memory requirements and then grow gradually as the size of the input stream grows. Unique counting sketches (Theta, HLL, CPC) actually reach a maximum size, beyond which they do not grow at all.  Quantile sketches can continue to grow but very very slowly (sub-logarithmically with the size of the input stream).

For example, a Theta Sketch configured with LgK = 14 (~16K) has a maximum size of about 256KB. However, with only one entry it consumes only 16 Bytes.

Our experience in using sketches in large systems is that the size of the input streams that feed the sketches tend to follow a power-law distribution.  Which means given a system total number of sketches of one million, the vast majority of sketches will have very few entries, and just a few sketches will be full size.   

> Note: If the sketches ingested into Druid are pre-aggregated sectors, for example, this power-law distribution in space required for the sketches is not as strong, as most of the sketches will already be at max size.  But in this case you are dealing with far fewer sketches, so the memory management concern may not be as severe.

To illustrate this power-law effect, I have created a toy model of space utilization in the attached excel spreadsheet:

[DruidModel_pwrLaw.xlsx](https://github.com/apache/incubator-druid/files/2696971/DruidModel_pwrLaw.xlsx)

For this model I assumed a power-law distribution of stream sizes from one unique to 134M uniques and a configured sketch size LgK = 14.  I adjusted the parameters so that the total number of sketches in the system is about one million.  

With these assumptions, the actual storage bytes required by all of the sketches is about 440MB.  However, allocating the full size of 256KB for every sketch would require nearly 35GB.  This results in a space utilization of about 1.27%!  This is a huge waste of memory! 

***
What I would recommend is that if we could work together, we could come up with a much more efficient memory management model for sketches in Druid that would allow you to recapture most if not all of that wasted space.  This will likely require some changes in Druid as well as a change in how sketches use and allocate memory.

One idea I have is to allow each sketch to self-allocate the space it needs as it grows. The sketch would be responsible for allocating new space and deallocating old space (especially for off-heap). 
What would live in the equal-sized slots of the Druid buffer would be a small, fixed sized "wrapper" with a pointer and a few other values, where the data structure of the sketch would be in an off-heap space managed by the sketch itself.  This means that Druid memory manager would have to allow for some amount of off-heap space that it is not controlling.  In the toy model above, that would be about 440MB of off-heap space.  The benefit is that Druid would get back nearly 35GB of off-heap space for other uses.  It seems like a big win to me, but I don't understand what changes would have to happen in Druid to make this work. 

We can certainly do the sketch work, but you (or someone deep into Druid) would have to make the appropriate changes in Druid.  One important aspect of the Druid work would be to provide some simple tools to analyze the actual distributions of stream sizes, sketch sizes and space utilizations before and after the change. This meta-data would be invaluable feedback for us to understand specific Druid customers' situations, and help us tune the system for even better performance going forward.

What do you think?

**Comment by gianm** [comment]
> I don't have a deep understanding of the inner workings of the memory allocation strategy in Druid, but I should point out that the current model of allocating equal sized slots in a Buffer where each slot is the maximum possible size of a sketch Is very likely a horrible waste of memory space.

Yeah, it's not ideal, especially not for some of the newer sketches. (The granddaddy of Druid sketches, hyperUnique, doesn't have a very high max memory footprint, so it was less of an issue back then.)

> What I would recommend is that if we could work together, we could come up with a much more efficient memory management model for sketches in Druid that would allow you to recapture most if not all of that wasted space. This will likely require some changes in Druid as well as a change in how sketches use and allocate memory.

That would be awesome.

Rather than the Druid memory manager allowing for off-heap space that it doesn't control, what if Druid _did_ control it, but basically delegated that control to the sketch? Druid's query engine works by allocating a fixed-size "processing buffer" to each compute thread. When a thread processes a segment, it allocates all the memory it needs out of that buffer. After the segment is done being processed, the results are transferred elsewhere, and the processing buffer is reused for the next segment to be processed. The processing buffers are typically 500MB to 2GB in size, and they are preallocated at server startup to avoid "surprises" (one buffer per compute thread, which is a fixed-size pool generally set to the number of processors).

Right now, as I'm guessing you know, the protocol for aggregators getting space in that buffer is something like:

1. Druid calls AggregatorFactory's getMaxIntermediateSize method to figure out how much memory to allocate per aggregator.
2. Druid allocates that much memory per grouping tuple.
3. Druid calls BufferAggregator's "init", "aggregate", and "get" methods to interact with the memory it has allocated.

Riffing off your idea, what I'm thinking is carving out a chunk of the processing buffer to be managed by the BufferAggregator impl:

1. Druid calls a new AggregatorFactory "getTypicalIntermediateSize" method to figure out a "typical" size per aggregator, and getMaxIntermediateSize to figure out the max.
2. Druid computes how many grouping tuples it could store in the buffer if each one had aggregators of the "typical" size. Call it N.
3. Druid carves out an arena of size N * getTypicalIntermediateSize from the processing buffer, and passes it to the AggregatorFactory's "factorizeBuffered" method, which creates a BufferAggregator that is free to use that arena.
4. For each grouping tuple, Druid stores not the aggregated value, but just the information needed to find the actual data in the arena.

We could also tweak this protocol to avoid the arena if "typical" equals "max", so primitive aggregators don't need to become more complex, and so we save the extra overhead for the pointer into the arena.

**Comment by gianm** [comment]
> I think you are referring to the HyperLogLog (HLL) sketch implementation that was developed for Druid some years ago. There are several things you need to understand about that implementation.

@leerho, yep, you are right, I am talking about that one. I am aware of the things you mentioned and appreciate the work you've done in the characterization studies (I was not aware of the problems with our core HLL implementation until that work was published). I only mentioned it by way of explaining why we never worried about growability in the past, back when that was the only sketch we supported.

It's a separate issue from this one, but, I'd like to take you up on working out a way to migrate users to the new sketch. It is somewhat delicate since the new one is in an extension and the old one is in core. And also because they don't have the same on-disk format, so we'd need to support both forever (we don't want to drop compatibility with on-disk data). We need to get the migration right to avoid user confusion.

> I'm not sure I follow your proposal and may be missing something.

What part is unclear? I can tell from your other comments that you are following at least the main idea of it: that each aggregation operator would get a chunk of memory and be responsible for using it to store sketch data for all the tuples being aggregated for a given segment.

> Nonetheless, one of the challenges of just carving out a chunk of the processing buffer to be managed by by the individual BufferAggregators is that in order truly gain back the "unused memory" would require memory management sophistication similar to the design of a malloc(), free() and a garbage collector, which is non-trivial. Imagine each sketch with an internal hash-table. As individual sketches grow they need to obtain a larger chunk of memory for a bigger hash-table, move their data into the larger chunk and free the previous chunk. If those freed chunks don't get reused, then we will not achieve the optimum memory savings. Allowing the sketches to allocate and free memory directly from the operating system allows us to leverage the already existing and very sophisticated malloc() and free() of the underlying C-libraries and the OS itself.

On the flip side, the challenge of _not_ using a chunk of the processing buffer is that we need two things to make that work:

1. A way for users to configure the maximum amount of 'extra' memory used per query, or some mechanism to set that limit automatically. (We can't allow unlimited allocation, since we'll risk running out of memory.)
2. A way to track the amount of memory being used per query, and if it exceeds the limit, trigger the out-of-memory code that would get triggered if the processing buffer filled up. Depending on where we are in the query pipeline and what engine is being used, that might trigger a spill to disk, a second pass through the data, an emitting of partially data to a later stage of the pipeline, or an error.

They are probably solvable, but I just wanted to call them out.

> BTW, there is already a mechanism in the JVM to track usage of off-heap memory used by DirectByteBuffers. We use this same mechanism to track allocations we make against off-heap memory even though we don't use DirectByteBuffers. So the JVM knows and tracks this usage already. Druid could also monitor these same JVM counters if it wanted or needed to.

Do you know if there's a way to use this functionality to track per-query memory usage? That would be ideal, since we don't want excessive memory use by one query to affect another unrelated query.

**Comment by gianm** [comment]
> Do you know if there's a way to use this functionality to track per-query memory usage? That would be ideal, since we don't want excessive memory use by one query to affect another unrelated query.

I suppose we could ask each aggregation operator to track its own 'extra' memory usage and report it to the query engine when asked. That sounds pretty easy. Which would just leave how we configure the maximum. I guess it'd be a new config, possibly defaulting to some percentage of the processing buffer size?

**Comment by leerho** [comment]
@gianm 

> I'd like to take you up on working out a way to migrate users to the new sketch. It is somewhat delicate since the new one is in an extension and the old one is in core. And also because they don't have the same on-disk format, so we'd need to support both forever (we don't want to drop compatibility with on-disk data). We need to get the migration right to avoid user confusion.

Understood and I agree that you will have to keep it around, but once we have an easy way for users to substitute in the DS HLL sketch, we should deprecate the old one with documentation on how to use the DS HLL sketch instead. The docs will have to include the warning that since the two sketches use different hash functions, using the DS-HLL sketch is starting from scratch.  If the user is relying oh historically stored sketch images, they are stuck with the old sketch, and its error problems.

Just wondering, is there a way we could move the DS library to core?

I am still on vacation this week, but will start looking at this next week :)

**Comment by gianm** [comment]
> Just wondering, is there a way we could move the DS library to core?

Potentially - it could also make sense to move hyperUnique from core to an extension. I am not sure what makes the most sense. I started a new thread for this, since it's off topic from this issue: https://github.com/apache/incubator-druid/issues/6814

On topic for this issue, have you got any more thoughts about how we might allow aggregators to allocate extra memory?

**Comment by leerho** [comment]
@gianm 

> Do you know if there's a way to use this functionality to track per-query memory usage? That would be ideal, since we don't want excessive memory use by one query to affect another unrelated query.

The mechanism I was referring to is in [Bits.java](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/nio/Bits.java#l618) and is for the JVM.  It is not thread specific so not directly useful on a query basis.  However, Druid could create its own query direct-memory tracking mechanism as an "extension" of the underlying JVM mechanism.  

The way we leverage the nio/Bits tracking mechanism can be found in [memory/NioBits](https://github.com/DataSketches/memory/blob/master/src/main/java/com/yahoo/memory/NioBits.java).

>  have you got any more thoughts about how we might allow aggregators to allocate extra memory?

No conclusions just yet. I will be studying this this week.

**Comment by leerho** [comment]
@gianm 
This topic has been inactive for a while, but the issue still exists.  As we have been integrating our C++ versions of our sketches into PostgreSQL we have learned about how they solve this problem.   Custom UDFs perform memory allocations and destruction using the Postgres supplied "palloc" and "pfree" functions. This way, Postgres can track and manage the allocation and free processes in the context of queries or transactions.  This way, when the contexts are closed, all the allocated memory can be guaranteed to be freed.  

Inside a specific aggregation function every allocation for space (for an array for example) is performed via these palloc and pfree functions.  The aggregation function does not have to live in a contiguous chunk of memory, which make the design of the aggregation function much easier.

**Comment by himanshug** [comment]
@leerho It appears that postgres does have a memory allocator in order to provide the "palloc" and "pfree" methods . @gianm was suggesting something similar. In that case DS library would allow some way of passing those functions . Druid(or other users of DS) would implement the memory allocator  in the way that makes most sense for them (e.g. allocating a big chunk of memory at startup and then giving off chunks from this in "palloc" or delegate each "palloc" to underlying jvm heap or os ...)
I looked into this a long time ago and one way was hacking it was to use "MemoryRegion" and "MemoryRequest" as in https://github.com/himanshug/druid/blob/growable_aggregator_final/extensions/datasketches/src/main/java/io/druid/query/aggregation/datasketches/theta/SketchResizableBufferAggregator.java#L120 (as you might guess this is based on pretty old version of DS library :) ) .

@gianm for IncrementalIndex , if above is done, simplest would be to use BufferAggregator and it would be more accurate as well than trying to do sizeOf(aggregator) . Current implementation to spill based on `getMaxIntermediateSize()` is puzzling to me as the number returned there is totally unrelated to what smallest/current/largest heap utilization of on-heap Aggregator would be. That number is only relevant when BufferAggregator is used.

**Comment by gianm** [comment]
I like the idea of using a chunk of the processing buffer (since it already exists, and because it doesn't incur any JVM heap operations or put any pressure on the GC) but I don't like the idea of trying to rebuild a fancy memory allocator. So I'm starting to wonder how simple of an allocator we can get away with.

I wonder how bad it would be if aggregators were never allowed to free memory. Basically, let them allocate whatever chunks they want, and free it automatically at the end of the query, but don't let them free it. And if the total allocated memory exceeds the memory limit for a query, then fail the query.

> @gianm for IncrementalIndex , if above is done, simplest would be to use BufferAggregator and it would be more accurate as well than trying to do sizeOf(aggregator) . Current implementation to spill based on getMaxIntermediateSize() is puzzling to me as the number returned there is totally unrelated to what smallest/current/largest heap utilization of on-heap Aggregator would be. That number is only relevant when BufferAggregator is used.

IIRC we talked a bit about this on the PR - yeah, it is a non-sequitur, but:

1. It's likely that the `getMaxIntermediateSize` for buffer aggregators is also a rough, but reasonble cap on how much on-heap memory might be used by an on-heap aggregator.
2. We considered moving IncrementalIndex's aggregators off-heap out of scope at the time.

**Comment by himanshug** [comment]
> I wonder how bad it would be if aggregators were never allowed to free memory. Basically, let them allocate whatever chunks they want, and free it automatically at the end of the query, but don't let them free it. And if the total allocated memory exceeds the memory limit for a query, then fail the query.

I intentionally left the detail of "pfree" implementation and I can imagine an interface for "MemoryAllocatorFactory"  interface (which has factory method with a parameter for supplier of os memory e.g. StupidPool ). Implementation could be as simple as possible including free() being noop and a close() method on allocator that gets called at the end of query and all memory is freed at that point only.


> We considered moving IncrementalIndex's aggregators off-heap out of scope at the time.
I meant if allocator stuff was in place then we could use an heap-based-allocator that gets used from OnHeapIncrementalIndex . I think it would be simple, but then you never know till you prototype :)

**Comment by leerho** [comment]
@himanshug @gianm 

> I looked into this a long time ago and one way was hacking it was to use "MemoryRegion" and "MemoryRequest" as in https://github.com/himanshug/druid/blob/growable_aggregator_final/extensions/datasketches/src/main/java/io/druid/query/aggregation/datasketches/theta/SketchResizableBufferAggregator.java#L120 (as you might guess this is based on pretty old version of DS library :) ) .

Those mechanisms still exist in the current library, the MemoryRequest was just renamed [MemoryRequestServer](https://github.com/DataSketches/memory/blob/master/src/main/java/com/yahoo/memory/MemoryRequestServer.java).   It is essentially the same as the Postgres concept and has been in the library long before we knew about Postgres.  The underlying implementation, of course, would be up to Druid.  

The library also has a [DefaultMemoryRequestServer](https://github.com/DataSketches/memory/blob/master/src/main/java/com/yahoo/memory/DefaultMemoryRequestServer.java) which just allocates from the heap if the primary interface has not been implemented.

Currently, only the DS-HLL, Theta, and Quantiles sketches are designed to take advantage of this.  But if the demand is there, we could update other relevant sketches in the library to also use this mechanism.  

The above MemoryRequestServer interface is pretty simple, but if it doesn't exactly meet your needs, let us know.  We would be happy to work with you as to what makes sense.

**Comment by himanshug** [comment]
one , I think more flexible for druid core code, alternative to https://github.com/apache/incubator-druid/issues/2963 is that 

add following method to `AggregatorFactory` 
```
  /* Smallest size ByteBuffer to use with BufferAggregator. This can be optionally overridden to support
  incremental size offheap buffers.
   */
  public int getMinimumOffheapSize()
  {
    return getMaxIntermediateSize();
  }
```

and  add `throws MemoryExceededException` to `BufferAggregator.aggregate(ByteBuffer buffer,int position)` method with contract that `MemoryExceededException` can only be thrown if `buffer` provided is of a smaller size than `AggregatorFactory.getMaxIntermediateSize()` and underlying sketch does need more space really.

With that druid code using `BufferAggregator` can work as follow...

start with a on/off heap `ByteBuffer` or size `AggregatorFactory.getMinimumOffheapSize()` , during aggregation if `MemoryExceededException` is raised then allocate another on/off heap `ByteBuffer` of double the size (optionally `MemoryExceededException` could have a variable telling what is minimum required increased size that `BufferAggregator.aggregate(..)` sets when throwing ex) and call `relocate(int oldPosition, int newPosition, ByteBuffer oldBuffer, ByteBuffer newBuffer)` and then carry aggregation forward.

now the question of how sophisticated the MemoryAllocator can or can not be is outside of aggregator implementation. I think it will be "enough" to let OS deal with it and use calls to `ByteBuffer.allocate(size)` (in OnHeapIncrementalIndex , use `BufferAggregator` instead of `Aggregator`) and `ByteBuffer.allocateDirect(size)` (in query engines)

We track the amount of memory used for these `dynamically sized aggregators` and have configurations to limit amount of memory usage.
For now, `dynamically sized aggregators` are the ones for which `AggregatorFactory.getMinimumOffheapSize() < AggregatorFactory.getMaxIntermediateSize()` .

When all druid code is updated to handle `dynamically sized aggregators` , we can actually remove `AggregatorFactory.getMaxIntermediateSize()` method altogether and add a `boolean AggregatorFactory.supportsDynamicallySizedAggregation()` and allow `BufferAggregator.aggregate(..)` to throw `MemoryExceededException` at anytime to support cases like `doublesSketch` where there is no known max size really.
We can probably also remove `Aggregator` interface at this point as well.

so overall we solve two problems...
1) not over-allocate/over-estimate memory
2) support full on off-heap aggregation for sketches where there is no maximum size e.g. `doubleSketch`

@gianm does that make sense,  if yes, I will probably extract this into  a separate proposal.

**Comment by gianm** [comment]
@himanshug, I think most of that idea is good, except I'd prefer a special return value from `aggregate` rather than throwing an exception, for two reasons: exceptions are expensive to generate, and also that this situation is not really 'exceptional' (certain aggregators might be expected to exceed min size somewhat often).

**Comment by gianm** [comment]
Are you still interested in writing up a proposal? Would you be interested in implementing this as well?

Btw, a couple things to think about-

1. Each ByteBuffer has some memory overhead, on the order of I think 30-60 bytes in the heap or something like that. So any dynamically growable aggregator that has to grow should choose its min size in order to avoid creating too many ByteBuffers.
2. Your proposed getMinimumOffheapSize is meant to be paired with getMaxIntermediateSize. It would be better if their names were more similar (getMinIntermediateSize?).

**Comment by himanshug** [comment]
@gianm thanks, will write a proposal today . I do plan to implement it (or at least some parts of the proposal to validate my own thinking)

> I'd prefer a special return value from aggregate rather than throwing an exception, for two reasons: exceptions are expensive to generate, and also that this situation is not really 'exceptional' (certain aggregators might be expected to exceed min size somewhat often).

I thought about expense of generating Exception and was thinking of disabling stacktrace creation in `MemoryExceededException ` class , but returning a value would do the job as well.

> any dynamically growable aggregator that has to grow should choose its min size in order to avoid creating too many ByteBuffers.

min size would be controlled by aggregator implementor and I would expect them to have default values but let it also be sent as part of XXXAggregatorFactory json spec  to provide full control to user because right min size may need to be fine tuned for specific dataset/queries/indexing

**Comment by gianm** [comment]
> min size would be controlled by aggregator implementor and I would expect them to have default values but let it also be sent as part of XXXAggregatorFactory json spec to provide full control to user because right min size may need to be fine tuned for specific dataset/queries/indexing

Yes, I was assuming this as well. I only mentioned the consideration in case it affects how you might implement growability for some of the builtin aggregators.

**Comment by gianm** [comment]
Did you end up writing a proposal @himanshug? I was looking around for it just now.

**Comment by himanshug** [comment]
@gianm https://github.com/apache/incubator-druid/issues/8126

**Comment by zenfenan** [comment]
This is still an issue. We are having `thetaSketch` based metrics and ingestion does a frequent flush with fewer records. For the time being, we have set `maxBytesInMemory` to -1 and configured `maxRowsInMemory` to a guesstimated number but would really help if we can have `maxBytesInMemory` to work since we can then have a segment at the recommended 500-700MB range.

**Comment by gianm** [comment]
Reopened; still an issue.
