### ISSUE TITLE
Druid SQL planning time can exceed query timeouts

### ISSUE THREAD

**Issue by JulianJaffePinterest** [apache/druid#7957]
### Affected Version

0.14.0-incubating

### Description

Based on our operational experience, Druid SQL query planning can exceed the configured timeout for a query. We've observed this in conjunction with #7904, where requests with large IN clauses (1k+ elements) cause elevated CPU usage on a broker node long after the the query times out. This appears to be due to SqlLifecycle either not respecting query time outs (instead relying on the generated native queries to time out if necessary) or due to the sql planning itself not being cancellable.

**Comment by gianm** [comment]
Timeouts are checked at various points in the query lifecycle (not continuously) so it does make sense that this can happen. Currently, the main points they're checked are:

- On historicals during query processing, depending on query engine and algorithm used, either between every row or between every segment
- On the broker, when it's reading data from historicals

Might be nice to add timeout checking in a few more places. However, for the specific issue in #7904, it probably wouldn't be interruptible since it's spinning inside Calcite code on something algorithmically excessive. That algorithmic excessiveness should just be fixed in Calcite itself and then the newer version of Calcite pulled into Druid.
