### ISSUE TITLE
Datasource availability mis-represented due to 0 row segments not cleaned up after compaction

### ISSUE THREAD

**Issue by acdn-mpreston** [apache/druid#8000]
### Affected Version

0.14.0, 0.14.2

### Description

After tracking the 'druid/coordinator/v1/loadstatus' API over weeks of execution, I started to notice long periods of time when our datasources would not be 100% available even though I could query all data from them successfully. Here is an example response:

{
    "npav-ts-metrics-15m": 100,
    "npav-ts-metrics": 97.31543624161074
}

When I look at the "missing" segments, I see the following in the unified-console:

![image](https://user-images.githubusercontent.com/33030320/60396911-483bae00-9b15-11e9-859b-c311b79fec48.png)

This shows that the data is there, and has been compacted, but there are also some '0-row' segments for the same time period that have not been cleaned up. These are being used to reduce the datasource availability even though the data is queryable.

Eventually these rows get cleaned up, but then new ones take their place, so the datasource is very rarely 100% available from the POV of the 'druid/coordinator/v1/loadstatus' API. Maybe these segments could be filtered out when handling the API to more accurately represent the status of the datasource?

**Comment by vogievetsky** [comment]
Hi @acdn-mpreston there is a lot to unpack in this issue.

1. You are issue number 8000, congratulations 🎆 

2. I am saddened by the issue your console is having rendering icons

  ![image](https://user-images.githubusercontent.com/177816/60402652-54d8fa00-9b47-11e9-94e2-cd39d6cf6202.png)]

  I am guessing you are somehow prevented from loading the icon font? This should be addressed in the newly released Druid 0.15.0 , we upgraded to the latest blueprintjs which no longer uses the icon font.

3. The segments you have highlighted do not really have 0 rows num_rows is only reported for available segments. This is confusing UI and will be fixed in the next iteration of the web console (in 0.16.0). It will then say `(unknown)`.

4. The segments you have highlighted are actually the segments you want! Look at the version it is higher. Maybe they are the result of the compaction and they have not been loaded yet?

5. More info is needed to understand what is going on: by `I started to notice long periods of time when our datasources would not be 100% available` what do you mean by 'long' minutes? hours? days? Also when you say `Eventually these rows get cleaned up` can you be specific on 'Eventually' is it minutes? hours?

**Comment by acdn-mpreston** [comment]
Hey @vogievetsky, thanks for the quick attention!

1. Thanks!!!
2. Awesome.
3. That makes more sense, thank you.
4. You are correct, I made an assumption based on the "Num rows" being populated and the "Is available" flag being set to true....interesting that there are 3 different versions of the segments all published at the same time.
5. For the datasource availability, majority of the time it has not been 100%. Here is a graph showing the availability returned over a couple day period where we call the loadstatus API every minute:
![image](https://user-images.githubusercontent.com/33030320/60519696-114ecf00-9cb2-11e9-9fe7-46f69ac1f80d.png)
Sometimes it will be 100% available, but not regularly. As you can see, it is almost always VERY close to 100% but not 100%. If I query the data, it is always there....no segments are missing it just seems that there is segment tracking that is confused.
In terms of resolution, it takes many minutes or even maybe an hour, to resolve the mis-represented segments.

**Comment by acdn-mpreston** [comment]
Also, @vogievetsky this may not be related but I notice that I did not have this issue when replication was reduced from 3 copies to just 1. This graph shows an example of this:
![image](https://user-images.githubusercontent.com/33030320/60521370-25480000-9cb5-11e9-875f-6eb23369fe6e.png)
Please keep in mind that some of the noise in the graph is due to some of our tests on this system, but the overall trend of having less frequent instances of datasource availability being less than 100% does still appear to be applicable.

In addition, please note that I am running a custom build based on this other issue currently under investigation: https://github.com/apache/incubator-druid/issues/7926

**Comment by acdn-mpreston** [comment]
@vogievetsky my latest test with replication enabled does not have this issue. It must be related to something else around how compaction is executing and not fully replacing the previous versioned segment files.
