### ISSUE TITLE
full-text search

### ISSUE THREAD

**Issue by ThreeEarthGod** [apache/druid#8015]
HI:
   Does druid support similar to solr full-text search and highlight word segmentation? How to support?

**Comment by niravmehta** [comment]
Druid has a nice [Search API](https://druid.apache.org/docs/latest/querying/searchquery.html). There are also some options to [refine how searches are performed](https://druid.apache.org/docs/latest/querying/searchqueryspec.html). 

It won't do stemming / stop word removal etc. Neither will it highlight matches in results. 

But I found it to be very useful implementation because: it's fast and even returns the dimensions where match occurred. 

Word highlighting can be easily implemented in your front-end app.
