### ISSUE TITLE
Support ingestion of datasketches quantile sketch built outside of druid

### ISSUE THREAD

**Issue by ashwanilabs** [apache/druid#8218]
### Description

Current version of doc for qualities mentions that its possible to ingest sketches built outside of Druid, but doesn't mentions any configuration for the same. From the code, it seems there is no option available as today to achieve that.

https://druid.apache.org/docs/latest/development/extensions-core/datasketches-quantiles.html

### Motivation

Just like theta sketches, this will enable users to ingest quantile sketches into the Druid.

**Comment by AlexanderSaydakov** [comment]
How did you reach the conclusion that it is not achievable? From what code?
I know this is being done every day.

**Comment by ashwanilabs** [comment]
Because I don't see any matching aggregator parameter like "isInputThetaSketch" for theta sketches. Do we have any thing similar parameter present for quantile sketches ? If yes, can you please update the documentation accordingly for quantile sketch.

**Comment by AlexanderSaydakov** [comment]
Theta sketch is to count distinct values of any type. This particular implementation of Quantiles sketch is specialized for estimation of numeric distributions, and this fact is used to automatically detect the input. If the specified input column is numeric, Druid aggregator builds a sketch from these values, otherwise it assumes that input contains sketches for merging.
