### ISSUE TITLE
[DISCUSS] Code generation for commonly implemented basic methods

### ISSUE THREAD

**Issue by jihoonson** [apache/druid#8328]
I recently found a bug in `ArrayOfDoublesSketchAggregatorFactory .equals()` (fixed in https://github.com/apache/incubator-druid/pull/8326) which made me think that we may need a better way to implement and maintain them. `equals()`, `hashCode()` and `toString()` are very commonly used functions and not easy to catch a mistake if ppl write them manually. To avoid mistakes, I usually use the code generation function of Intellij. This function is good but is not enough to automatically maintain those implementations on code changes.

The [Lombok](https://projectlombok.org/) is a library to address this kind of use case. It can automatically generate codes of `equals()`, `hashCode()`, and `toString()` at compile time so that we can expect the implementations are always up to date. Also, they are programmatically generated and it's safer than human codes.

I also find the Lombok library useful when the [builder pattern](https://en.wikipedia.org/wiki/Builder_pattern) is useful. It provides an annotation called `@Builder` which automatically generates a builder implementation for a class. This could be very useful to maintain the test codes for user-facing configuration classes. For example, I have added a couple of new configurations to `ParallelIndexTuningConfig` which also required to fix all places calling the constructor of the class. With the builder, I think we can reduce the required changes which could reduce the PR size.

The downside of using a library such as Lombok is the build time might be longer since it needs to generate more source codes. But I still think it would be worth to take it.

If we go with this way, I think we can start with `equals()`, `hashCode()` and `toString()` methods and gradually change those implementations with Lombok annotations (like 10 classes in each PR). Probably we need unit tests as well if those methods of a class only take account into only a subset of variables defined in that class.

Welcome any thoughts.

**Comment by ccaominh** [comment]
I've also seen instances where new fields are added to classes but one or more of `equals()`, `hashCode()`, or `toString()` were not updated to account for the new field. Adding tests to catch these kinds of errors is not very productive, so using lombok to automatically generate methods like these is helpful. I also find lombok useful to generating getter/setters for DTOs, for similar reasons.

The lombok builder generator is very useful and will make the code more readable in places like this:
```
           new IndexTuningConfig(
                null,
                10000,
                10,
                null,
                null,
                null,
                null,
                null,
                null,
                indexSpec,
                null,
                3,
                false,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            )
```

It's also possible to easily [ignore the lombok-generated methods from code coverage](https://www.rainerhahnekamp.com/en/ignoring-lombok-code-in-jacoco/), making the code coverage reports more useful.

Some possible drawbacks of using lombok:
- Slower IDE performance (since it has to delombok the code to index it)
- "Missing" code for IDEs/editors without lombok plugins (although most of the popular IDEs, like Eclipse and IntelliJ, do have support)
- Debugging/callstacks do not match the source code

Overall, I think the advantages of lombok outweigh its drawbacks. If we do start using lombok, however, I think we should add its [experimental features](https://projectlombok.org/features/experimental/all) to the forbidden apis list.

**Comment by clintropolis** [comment]
This seems an interesting idea, but we have to be _very careful_ when doing and reviewing this to make sure we don't lose any purposeful omissions or customizations done for performance reasons. I'm thinking of [things like this](https://github.com/apache/incubator-druid/pull/6488/files#diff-804f39ab6702c58b3d422f90625fee48R225) where a large or expensive to work with field is left out of all of those things on purpose. It might be very hard spot all of these if they are not documented, so this is potentially risky in that regard.

**Comment by jihoonson** [comment]
@ccaominh @clintropolis thank you for the comments.

> I'm thinking of [things like this](https://github.com/apache/incubator-druid/pull/6488/files#diff-804f39ab6702c58b3d422f90625fee48R225) where a large or expensive to work with field is left out of all of those things on purpose. 

This is a very good point. I guess this could be one of the reasons why we should change only a few classes per PR.

**Comment by surekhasaharan** [comment]
Another example, where standard equals is not used for performance reasons is [here](https://github.com/apache/incubator-druid/blob/master/core/src/main/java/org/apache/druid/timeline/DataSegment.java#L369), there might be more.  So perhaps Lombok can be used or not on a case by case basis.

**Comment by jihoonson** [comment]
You can control what fields will be only considered in `equals()`, `hashCode()` (https://projectlombok.org/features/EqualsAndHashCode). I think you can do the same thing for `toString()`.

**Comment by himanshug** [comment]
IMHO, That is too magical. When I look at the source code, I want to know what is actually running ... e.g. if there is a stack trace from production server with line numbers for files inside druid source code etc, I would look at the source code that is checked in whereas actual code running is the rewrite from Lambok. That would add another variable to debugging equation for me to wonder is it possible that code generated by Lambok is buggy in some way. 
also, this is confusing for debuggers.

When I am browsing through the source code and there is a line say... `xx.equals(yy)` and I tell the IDE to goto the place where `equals(..)` is defined, it would take me to wrong place most likely. (Same goes for other things generated e.g. getters/setters, in fact with getters I don't know if we can declare those variables final)

OTOH It might be good to have something that can catch such issues and fail the build so that we can go fix it by writing/ide-generating that code manually.

**Comment by ccaominh** [comment]
Some (Java) alternatives to lombok to generate boilerplate with less magic are [AutoValue](https://github.com/google/auto/blob/master/value/userguide/index.md) and [Immutables](https://immutables.github.io/).

**Comment by leventov** [comment]
Prev. discussion about AutoValue: #4125

**Comment by himanshug** [comment]
I read through https://github.com/google/auto/blob/master/value/userguide/index.md and `AutoValue` does sound relatively better considering it generates new classes.
there would be some bunch of annotations needed to make json serde of those objects work,and also probably you need to define constructor with json annotations in the abstract class . anyways, my first impression is that it could be made to work.
there is a warning mentioned,  "Be careful that you don't accidentally pass parameters to the generated constructor in the wrong order. You must ensure that your tests are sufficient to catch any field ordering problem." tells that you still need to carefully unit test or else someone just changing ordering of getters in abstract class could introduce silent bugs.

**Comment by jnaous** [comment]
I would vote +2 for Lombok. People who haven't used Lombok usually assume that it's too much magic and that it makes it hard to debug. In my experience this has not been the case. Lombok makes it easy to delombok methods if you want to debug that piece through a single click in the IDE, and the methods are usually so simple and boilerplate that there really should be no bugs in it. I would trust automatically generated code that is tested by tons of people using it over manually added code by a developer who might miss a field in the equals or hashcode method. 

Lombok also does take you to the right place when you step through the code (to the relevant Lombok annotation).

In fact, I find that Lombok makes debugging easier by reducing boilerplate in code so you don't have to worry about it and makes the code much easier to understand and maintain.

**Comment by jihoonson** [comment]
I believe the issue with the debugging here is not the debugging with IDE but the debugging with your brain based on the stack trace. It will be still not good enough if we want to delombok first to see the real line number. I also believe the benefits @jnaous mentioned can be applied to other code generation tools in general, not only for lombok. I didn't have a time to look at AutoValue and Immutables. Will take a look soon.

**Comment by suneet-amp** [comment]
>  Adding tests to catch these kinds of errors is not very productive

I've run in to this problem as well - EqualsVerifier has been pretty effective in catching these types of errors and takes almost no time to write - https://jqno.nl/equalsverifier/

```
@Test
public void equalsContract() {
    EqualsVerifier.forClass(Foo.class).verify();
}
```

**Comment by ccaominh** [comment]
Another bug that could have been prevented by auto-generating `equals/hashCode/toString`: https://github.com/apache/incubator-druid/issues/8866

**Comment by jnaous** [comment]
@jihoon, I'm curious if you've had experience trying out something like
Lombok. I have never heard complaints about difficulty debugging from the
people who have worked with it. @suneet @chi, please chime in if you have
heard otherwise.

**Comment by jihoonson** [comment]
I used lombok in my previous company. I had a pretty good experience with that because I was involved in a medium-sized project and the code generation was pretty convenient and useful for that size of project. However, it was still sometimes annoying since it makes the IDE slower and I had to delombok for debugging. I would think this will be more emphasized with a big project like Druid.

I still didn't have time to check other libraries. @jnaous what is your rationale for using lombok other than others? What is the benefit we can get with lombok particularly?

**Comment by jnaous** [comment]
I like Lombok vs others because it hides boilerplate and reduces the amount
of code to maintain. Generally, if you assume that the boilerplate
generated by Lombok is correct (99.9% of cases) then it reduces the
cognitive load needed to debug issues and allows you to more quickly find
the actual sources of issues. It also reduces the effort of updating code
when you add a field.

That said, I would only advocate it for straightforward objects (like
immutable data objects used for serialization) and for real boilerplate,
nothing too fancy.

**Comment by suneet-amp** [comment]
I've never had to debug code generated by lombok, because it's always used for very simple code - hashCode&equals, trivial getters & setters, Constructors and Builders. And in my experience, I haven't seen the IDE slow down significantly because annotation processing was enabled for lombok.

There are some fancy features in lombok - like SneakyThrows that I think we should not use except within the test folder.

**Comment by suneet-s** [comment]
Thanks for the reminder stalebot! 

Does anyone want to try out using lombok so we don't need to keep adding EqualsVerifier tests for every class? I'm happy to be the first guinea pig in my next PR. We'd have to update the dev environment setup docs, but I think lombok would make the codebase nicer to read because you'd only have to read code that's interesting.

**Comment by jihoonson** [comment]
Sorry, I was thinking to test out all those libraries we discussed here, but have never got to it. I quickly checked AutoValue, Immutables, and Lombok today, and it seems Lombok might suit our needs most because we often add more methods in the "value" classes which seems not possible in other libraries since they generate concrete classes based on the annotated interface (I quickly read the docs of them, so could be wrong). It might be arguable whether it's a good practice or not, but that's what we have now. Also, [I remember wrong about the line number changes and Lombok doesn't change the line number in stack trace](https://stackoverflow.com/questions/37908097/line-numbers-generation-with-lombok). My other concern was about potentially slow response of the IDE but I think it could apply same for other libraries as well. I would vote for trying it out and seeing if there is any other issue.
