### ISSUE TITLE
Druid SQL - natively support mathematical functions ROUND(), RADIANS(), EXP(), LN(), POWER(), RAND()

### ISSUE THREAD

**Issue by ntkawasaki** [apache/druid#8661]
### Description

Currently these widely known mathematical operations are not officially implemented by Druid SQL:

```
Remote driver error: RuntimeException: org.apache.calcite.tools.ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 1, column 18 to line 1, column 23: 
No match found for function signature RAND() -> ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 1, column 18 to line 1, column 23: 
No match found for function signature RAND() -> CalciteContextException: From line 1, column 18 to line 1, column 23: No match found for function signature RAND() -> SqlValidatorException: No match found for function signature RAND()
```

Similar error for all. 

These functions used to work in Druid version 0.10 when the `useFallback` option existed, calcite had a way to call these. However it looks like this parameter has been deprecated since 0.15: https://github.com/apache/incubator-druid/commit/c648775b5b9001dafd26192abf2a61f44bfc16d4 and https://github.com/apache/incubator-druid/pull/7567

The docs here claim that these functions _do_ exist: https://druid.apache.org/docs/latest/querying/sql#numeric-functions

However I believe these are out of date, or had been written at an earlier time/version when `useFallback` was being used and they were callable.

### Motivation

These would be useful for Business Intelligence applications connecting to Druid SQL clusters, and are very well known operations for any numeric data.

**Comment by gianm** [comment]
Hi @ntkawasaki, Druid does support all of those functions today except `RAND`. Most of them were added in version 0.15. (You can access old Druid docs at e.g. https://druid.apache.org/docs/0.14.0-incubating/querying/sql; note that the 0.14 docs don't include most of these functions.)

I raised an issue specifically for `RAND`: https://github.com/apache/incubator-druid/issues/8789, which is still missing today.

Btw, we deprecated and removed `useFallback` because it led to unscalable query plans in many cases. We found that often, queries with `useFallback` would pull all raw data into the Druid Broker and process it there, which was a bad approach for big datasets. This risk outweighed the benefits, and so we decided to implement more functionality in Druid's native query system instead of relying on SQL interpreter fallback.

**Comment by ntkawasaki** [comment]
Thanks @gianm 

Made a Druid 0.15 database and its all good:

<img width="1551" alt="Screen Shot 2019-11-15 at 1 40 12 PM" src="https://user-images.githubusercontent.com/28987971/68977597-73195c80-07ad-11ea-82d5-c011e429ef7f.png">

We can come up with a workaround for RAND() until thats native in Druid.
