### ISSUE TITLE
Document how to run micro-quickstart or nano-quickstart in a docker container

### ISSUE THREAD

**Issue by leventov** [apache/druid#8926]
This [doc page](https://github.com/apache/incubator-druid/blob/94298f780927923b84f3127ec07c84cb5b115145/docs/operations/single-server.md) says micro-quickstart and nano-quickstart are supposed to be run in Docker container but I cannot find a step by step documentation anywhere about how to do that.

FYI @jon-wei

**Comment by jon-wei** [comment]
Hm, when I wrote that section for nano-quickstart, I was just using Docker containers as an example of resource constrained environments without intending for it to always be used with Docker.

That said, I agree that a Docker-oriented "getting started" flow could be useful to document, some have asked for it: https://github.com/apache/incubator-druid/issues/8702

I saw we have https://hub.docker.com/r/apache/incubator-druid, so maybe we could reference that instead of nano-quickstart for a Docker quickstart, but I'm not 100% caught up on our Docker support/story presently

**Comment by leventov** [comment]
> I saw we have hub.docker.com/r/apache/incubator-druid, so maybe we could reference that instead of nano-quickstart for a Docker quickstart

If so, for what reason nano-quickstart exists? If it's not supposed to be run in Docker (somehow), it doesn't make sense to mention that in the doc.

Also, I thought that nano-quickstart is a set of configurations that could be used in conjunction with an already existing Druid docker image. Or all configurations are baked into the image and a different image should actually be prepared for nano-quickstart?

**Comment by jon-wei** [comment]
> If so, for what reason nano-quickstart exists? If it's not supposed to be run in Docker (somehow), it doesn't make sense to mention that in the doc.

It's just a small example configuration not targeted at any specific deployment method, I think it's fine to remove the Docker reference there if you think it's confusing

**Comment by bsyk** [comment]
The published container (https://hub.docker.com/r/apache/druid) does not work for running these quickstart scripts. The os does not include bash or perl, which are both required to run the quickstart scripts.

Here's a minimal Dockerfile that does work with the quickstarts.
Perhaps the official docker image should use an os image rather than the java image as its base?

`ARG DRUID_VER=0.22.1

FROM apache/druid:${DRUID_VER} AS druid

FROM ubuntu:bionic
RUN apt-get update && \
    apt-get install --yes openjdk-8-jre-headless perl-modules && \
    apt-get clean

RUN addgroup --system -gid 1000 druid \
 && adduser --system --uid 1000 --disabled-password --home /opt/druid --shell /bin/bash --group druid

COPY --from=druid --chown=druid:druid /opt/druid /opt/druid

WORKDIR /opt/druid

USER druid

EXPOSE 8888/tcp
EXPOSE 8081/tcp

CMD ["bash", "-c", "/opt/druid/bin/start-nano-quickstart"]
`
