### ISSUE TITLE
does datasketches support the analysis "how many users have done X followed by Y" rather than simply "X and Y"?

### ISSUE THREAD

**Issue by yongmeibian** [apache/druid#8943]
What we need from funnel analysis is "how many users have done X followed by Y" rather than simply "X and Y".Can we achieve this with theta sketches?

**Comment by leerho** [comment]
@yongmeibian 

Note: We would have seen this much earlier if you had submitted this question to our [datasketches issues](https://github.com/apache/incubator-datasketches-java/issues) rather than here.

Nonetheless, we do not have a single sketch that addresses this problem directly.  But I imagine that this problem could be solved using multiple Tuple sketches with a little customization using generics.   

The problem you might face is that the Druid aggregation layer does not expose the generic interfaces, so you would have to interface whatever you come up with the Druid aggregators.

This is an interesting problem and is an inspiration to create a more flexible interface to the Tuple sketch family that would allow an easier way to do this kind of query.   When I have some time I will think about it.

Cheers,
Lee.
