### ISSUE TITLE
Prohibit assigning ScheduledExecutorService into ExecutorService

### ISSUE THREAD

**Issue by leventov** [apache/druid#9286]
It's needless, a simple ExecutorService should be created instead.

This Structural Search pattern finds two occurrences in the codebase: 

```
      <searchConfiguration name="Create a simple ExecutorService (not scheduled)" text="$x$ = $y$;" recursive="true" caseInsensitive="true" type="JAVA" pattern_context="default">
        <constraint name="__context__" within="" contains="" />
        <constraint name="x" nameOfExprType="java\.util\.concurrent\.ExecutorService" expressionTypes="java.util.concurrent.ExecutorService" within="" contains="" />
        <constraint name="y" nameOfExprType="java\.util\.concurrent\.ScheduledExecutorService" expressionTypes="java.util.concurrent.ScheduledExecutorService" exprTypeWithinHierarchy="true" within="" contains="" />
      </searchConfiguration>
```

Worth experimenting with variable or field declarations, too.

**Comment by mgill25** [comment]
Hi. I'd like to gently start off contributing to Apache druid, and would love to pick up this issue. 

If I understand correctly, for the two instances in this search, I should make sure that a regular `ExecutorService` is created for the variables instead of `ScheduledExecutorService`. I suspect there are already concurrency utility functions that help in doing that within the codebase that I can use? I'm not at all familiar with the codebase, so I will appreciate any guidance towards how to go on about fixing these issues.

Thank you!

**Comment by leventov** [comment]
> I suspect there are already concurrency utility functions that help in doing that within the codebase that I can use?

Yes, in `Execs` class
