### ISSUE TITLE
Druid-0.17: Bad ingestion spec generation from Data-loader UI 

### ISSUE THREAD

**Issue by v-vishwa** [apache/druid#9694]
When ingesting raw data from the actual JSON data source, Dataloader UI gives an option under ConfigureSchema step to decide/add/delete: dimension and matrices.

**Test Data:**

```
{"timestamp":"2019-10-21T21:31:01.498Z","dim1":"dim1","dim2":"dim2,"dim3":"dim3","m1":10}
{"timestamp":"2019-10-21T21:31:01.498Z","dim1":"dim1-2","dim2":"dim2-1","dim3":"dim3-1","m1":20}
{"timestamp":"2019-10-21T21:31:01.498Z","dim1":"dim1-2","dim2":"dim2-2","dim3":"dim3-2","m1":5}
{"timestamp":"2019-10-21T21:31:01.498Z","dim1":"dim1-3","dim2":"dim2-3","dim3":"dim3-3","m1":10}
```
Let's consider two cases:

**case-1)** If ROLLUP=FALSE: all the fields(dim1,dim2,dim3,m1) will be ingested as Dimensions.

**case-2)** If ROLLUP=TRUE: DataLoader UI decides automatically, sum_m1 (long_Sum) on a field m1 as a metrics and generate the ingestion specs accordingly which is perfect,But

While Re-indexing from already existing data source ( which has been ingested as per Case-1(Rollup=false),ConfigureSchema step reads all fields as Dimensions with RollUp-disabled,

When Rollup is enabled here, DataLoader UI decides sum_m1 (long_Sum) on field m1 as a metric( same as Indexing),
meaning the user is deciding to usem1as metrics, But this does not work post-Re-ingestion,Sum_m1` turns out to zero, however, data loader UI shows it perfectly:

<img width="1678" alt="Re-indexing-RollUp_True" src="https://user-images.githubusercontent.com/51313197/79152245-7b6fd500-7de9-11ea-8ddf-1273ad4ada41.png">

One need to add metrics in inputSource in the Re-indexing ingestionSpec to make it work: Eg

```
"inputSource": {
    "type": "druid",
    "metrics": [
      "m1"        <--=============---
    ],
    "dataSource": "orig",
    "interval": "2000/3000"
  }
```
**Is not DataLoader should automatically generate the JSON with the required metrics under InputSource ? This seems a UI DataLoader  .**

**Comment by vogievetsky** [comment]
Hi, sorry this fell between the cracks. I just retested it on Druid 24.0 and I can not repro this behavior. I assume something got fixed as a by product. If `metrics` is not set on the input source the expected behavior is to select all metrics.

Also with the new [SQL based ingestion](https://druid.apache.org/docs/latest/multi-stage-query/index.html) (and [re-ingestion](https://druid.apache.org/docs/latest/multi-stage-query/examples.html#insert-for-reindexing-an-existing-datasource)) this is definitely not an issue.
