### ISSUE TITLE
why doesn't Druid delete small segments after compact task complete?

### ISSUE THREAD

**Issue by FrankChen021** [apache/druid#9755]
compact is very useful to merge small segments into larger one. as small segments have been merged, they are still kept in deep storage and metadata storage.

i don't understand why those small segments are kept after compact task has finished. To keep those  small segments in deep storage usually is not a problem, but too many metadata records of those small segments might be performance penalty.

in our product environment, there're more than 30W segments records in metadata storage, most of them are marked as `unused` by compact task. Some queries as below on `druid-segments` table takes more than 5 seconds, which are considered as slow query from our DBA's view. 

````
SELECT payload FROM druid-segments WHERE used=true
````

Druid DOES provide 'kill' functionality to allow us the delete the `unused` segments. to use it to delete `unused` segments may cause problems:

1.  there're lots of datasources, it's painful to delete the unused segments one by one, especially when auto compaction is enabled. Or we can use HTTP API to simplify it, but it's still complex.

2. segments dropped by DROP RULES are also marked as `unused`. it's very hard to tell which segments are dropped, which unused segments are for compact. we don't want to delete those segments temporarily dropped by DROP RULES because the retention rules might be changed.

so why doesn't druid delete those small segments as soon as new larger segments are generated and loaded?

**Comment by jihoonson** [comment]
Hi @FrankChen021, Druid doesn't delete any data by itself even after compaction because you may want to revert the last compaction for some reason such as wrong compaction schema, or even a bug in compaction task. In your case, I think the auto unused segment cleanup by the coordinator may be useful. You can enable it by setting `druid.coordinator.kill.on` to true. You may also want to set `druid.coordinator.kill.durationToRetain` to avoid cleaning up unused segments too early. With this way, you can have some unused segments created by compaction for `durationToRetain` as well, but I guess it could be acceptable.

**Comment by FrankChen021** [comment]
Hi @jihoonson  With those two parameters you suggest, the unused segments after compaction could be DELETED both from meta storage and deep storage. but before the coordinator issues the delete task, these unused segments might still cause the slow query problem and take more storage space.

for example, there's a retention rule for default tier for 3 months and a drop rule to drop forever beyond 3 month. Because i want keep the data in deep storage for another 3 month, and i don't want coordinator deletes the unused segments marked by this drop rule, so `druid.coordinator.kill.durationToRetain` will be set to `PT6M`, which means all the unused segments will be kept for 6 months.

in our case, there're more than 20GB data put into druid, and more than 1200 segments will be generated every day(all the segment granularity is 'PT1H').  And everyday we compact these segments together, which results in  about another 400 segments. That means in total, there will be (1200 + 400) * 30 * 6 = 288,000 segments in the 6 months period.

this number might be acceptable now. but if we want to keep the data in deep storage for longer time, or the data stored in druid grows rapidly day by day, unused segments waiting for deletion after compaction will be more and more.

As there's a way to allow coordinator kills unused segment, i think it's reasonable to provide a way for user to delete unused segments after compaction. considering the scenario you mentioned that user might want to revert data, if it's plausible to provide parameters to do the auto deletion ? For example, a parameter named as `enabled` controls whether we enable the auto deletion function, another parameter named as `durationRetention` controls how long the unused segments will be kept after compaction if `enabled` is enabled.

**Comment by jihoonson** [comment]
> As there's a way to allow coordinator kills unused segment, i think it's reasonable to provide a way for user to delete unused segments after compaction. considering the scenario you mentioned that user might want to revert data, if it's plausible to provide parameters to do the auto deletion ? For example, a parameter named as `enabled` controls whether we enable the auto deletion function, another parameter named as `durationRetention` controls how long the unused segments will be kept after compaction if `enabled` is enabled.

@FrankChen021, sorry for late reply. I think it makes sense to support automatic cleanup after compaction. I'm not sure yet what those configurations would be though. `durationRetention` would depend on time when compaction completes, which might be hard to apply to all segments consistently. Maybe `numGenerationsToKeep` could be better which means the number of segment generations after compactions or overwrites?

**Comment by FrankChen021** [comment]
@jihoonson I don't understand how segment generations work. Let me give my understanding as below. 

1st, it's a property on a segment; 
2nd, its value will increase after compaction or overwrite. And if the new value reaches the value of `numGenerationsToKeep`, the old ones will be deleted. 

Is that right ? If it's, my question is,  if the value of `numGenerationsToKeep` is 3, does that mean the old segments will be deleted after compaction for 3 times ?

**Comment by jihoonson** [comment]
Ah sorry for missing details. For the generation of segments, it's similar to what you understand. It means how many overwrites have done before the most recent segments. So, the first generation of segments can be the very initial set of segments in a time chunk. The second generation can be another set of segments which were created by an overwrite task and have a higher version than the first generation segments. But, I didn't think storing the generation information anywhere since it would be only used for auto cleanup. Instead, you can check how many generations are in a time chunk when you retrieve segments from metadata store. So, given `numGenerationsToKeep = 3`, the auto cleanup task can remove the segments older than 3 generations if there are any. In that way, we can safely keep the most recent couple of generations of segments. You can keep only the latest generation if you want.  Does it make sense?

**Comment by sub007** [comment]
Any updates on this?

**Comment by sub007** [comment]
A ray of hope from @sergioferragut here - 
https://apachedruidworkspace.slack.com/archives/C0303FDCZEZ/p1687887042220139?thread_ts=1680814541.209289&cid=C0303FDCZEZ
