### ISSUE TITLE
Router strategies does not affect SQL query

### ISSUE THREAD

**Issue by Fullstop000** [apache/druid#9886]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

0.17.0

### Description

I've used a javascript router strategy to pick brokers by query priority. The strategy works well for native queries but it seems never affecting SQL queries.

The strategy will print the query if it's captured by this strategy. But I never see a SQL query being printed.
```
druid.router.strategies=[{"type": "javascript", "function": "function (config,query){print(query);if(query.getContext){var context=query.getContext();var priority=context.get('priority') || 0; print(priority);var m=config.getTierToBrokerMap();var size=m.values().size();if(size>0){var broker = priority>10?m.values().toArray()[0]:m.values().toArray()[size-1]; print(broker); return broker;}}return null;}"}]
```

**Comment by gianm** [comment]
Hmm, this is because the Router does not understand SQL, and just passes it to the Broker directly. It would be tough to fix this without introducing the SQL layer into the Router, which would be a pretty heavyweight thing.

One thing we had discussed previously was moving the Router logic into the Broker (so Brokers can route to each other). This might be a good path forwards.

/cc @clintropolis — may depend on the Broker asyncification stuff you had mentioned at one point.

**Comment by Fullstop000** [comment]
I find that the tier selecting strategy accepts `Config` and `Query` as args. Maybe we can just treat SQL request as a `Query`？
