### ISSUE TITLE
Geographic Queries x/y lon/lat coordinate confusion

### ISSUE THREAD

**Issue by lokkju** [apache/druid#9970]
The geographic query documentation is unclear about the relation of latitude/longitude to horizontal/vertical and x/y coordinates for querying.

### Affected Version
0.18.0 (all versions that support spatial queries?)

### Description
In Geography: `longitude` is the horizontal dimension and `latitude` is the vertical dimension
In Geometry: `x` is the horizontal dimension and `y` is the vertical dimension 
For Polygons: `abscissa` is the horizontal dimension values and `ordinate` is the vertical dimension values

The Geographic Query documentation page has an example that shows indexing dimensions being given as: `"dims": ["lat", "long"]`.

The spatial filter documentation for `rectangular` and `radius` bounds specifies queries should provide coordinates as `[x, y, z, …]`

This is confusing, and if followed to the letter, won't work as expected. Either I'm misunderstanding something, or else the person who wrote the documentation didn't understand the difference between geographic coordinate order vs geometric coordinate order.

The same issues exists with `polygon` bounds, as providing the index dimensions as in the example will require the `abscissa` to contain latitude (vertical) values.

The correct fix would be to specify your index dimensions as `["long","lat"]`, but that could be very confusion for anyone who has already been using spatial queries. An alternative is to enshrine the `["lat", "long"]` ordering by specifying that spatial bounds should provide coordinates in ["lat", "long"]`  order.

**Comment by SWH12** [comment]
Druid's Geographic Queries is not a real Geographic Queries. So the documentation don’t care about the relation of latitude/longitude to horizontal/vertical and x/y coordinates for querying.

**Comment by lokkju** [comment]
But it does care, as it uses the terms `lat` and `long` in the example; but it uses them as `x` and `y`, when they are actually `y` and `x`. As I said, this means that anyone who follows the example, and then queries using, for instance, correct `polygon` coordinates, will not get correct results.

Perhaps the most simple fix would be to remove the usage of the terms `lat` and `long` from the page entirely.

**Comment by francisco-metricell** [comment]
I second the suggestion from @lokkju. For those trying to use the spatial features of Druid with the current documentation, they will likely fail to see that the order of the dimensions used in the spatial ingestion spec must be equal to the order of the dimestions used in the filtering spec.

Since, as @SWH12 correctly explained, the geographic queries are not actually geographic but instead **geometric** queries, removing all mentions of latitude and longitude from the documentation and replacing with `x` & `y` will be beneficial for the users.

**Comment by superivaj** [comment]
I second the suggestion from @lokkju. For those trying to use the spatial features of Druid with the current documentation, they will likely fail to see that the order of the dimensions used in the spatial ingestion spec must be equal to the order of the dimestions used in the filtering spec.

Since, as @SWH12 correctly explained, the geographic queries are not actually geographic but instead **geometric** queries, removing all mentions of `latitude` and `longitude` from the documentation and replacing with `x` & `y` will be beneficial for the users.
