### ISSUE TITLE
Loss of sub-second time info when parsing posix-formatted time field

### ISSUE THREAD

**Issue by enenuki** [apache/druid#9991]
Hi, 
we are using kafka supervisor to ingest data and we seem to have issue with loss of precision while parsing posix-formatted time field.
Input data is formatted as in: 
`{"host":"somehost.hr", "ident":"dpdk", "pid":"182", "msgid":"-", "extradata":"-", "message":"Some msg", "severity":"err", "severity_val":3, "facility":"daemon", "facility_val":3, "priority_val":27, "tag":null, "time":1591349534.205346}`
Note that time is posix format, but as DOUBLE not as integer, so it contains info about milli/nano seconds.

Time specification in kafka supervisor is:
`"timestampSpec":{ "column":"time", "format":"posix" }`

However, after ingestion we get data rounded to second.

Maybe we are doing something wrong? 
Is there any way we can get this sub-second time preserved? We found that in transformation expressions  we can refer to "original" time field (used to populate __time field), but this seems like hacky solution.

Version of druid is 0.18.1

Thanks!

**Comment by FrankChen021** [comment]
posix timestamp is a value of SECONDS since epoch. Druid takes the input as type of LONG, so the fraction is ignored. To keep the subsecond, you could turn the value into format of MILLISCONDS timestamp, that is 1591349534205 in your example. 

In practice, query granularity is widely used to  utilize the roll-up functionality, which means there's no need to care about the exact timestamp of every record. Because of loss of subsecond, it's equivalent to set the query granularity to SECOND. So I think the loss is acceptable.

**Comment by enenuki** [comment]
Thanks for your quick response.
I did not understand you exactly... you are suggestion to change our input format or we can do some pre-time parsing transformation to achieve this?
We plan to use rollup functionality but with minimal none/millisecond query granularity. Seconds as query granularity is not an option.
Still, getting input as double and than ignoring sub-second info seems somewhat unreasonable. Especially if you do have an option to use millisecond granularity. Maybe this affects ingestion time?

**Comment by FrankChen021** [comment]
I mean you can do pre-time transformation to turn the value from double into format of milliseconds.

Ignoring the sub-seconds is reasonable because [according to the definition of POSIX time](https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xbd_chap04.html), it's SECONDS since epoch.  I don't see any document take it as a number with fraction

**Comment by jihoonson** [comment]
Hi @enenuki, the `posix` timestamp format rounds timestamps to second. Does `millis` timestamp format work for you?

**Comment by FrankChen021** [comment]
@jihoonson `millis` timestamp doesn't work, neither does `micro` or `nano`. All of these format require value of integer.

**Comment by enenuki** [comment]
@jihoonson Unfortunately we get the input time as posix double number not long. 

And FrankChen021 is right, posix standard does state number as integer... 

Not sure which options do we have without changing input format... All transformations take place only after time-parsing so we cannot use __time field? If that is right we do not have much options... 

The only option that we currently use is using transformation expression to calculate ID by using the original field used to populate __time. This field is available in transformation expressions so this enables us to use it to generate new filed with milliseconds preserved...
